### ISSUE TITLE
Connection refused for Medis, Redis-commander with Custom redis.conf

### ISSUE THREAD

**Issue by MichelDiz** [docker-library/redis#104]
I'm able to load Config. I had commented in an issue that it was about loading problems. So my issue is completely different.

Redis works perfectly inside the container through the CLI, but when exposing the port to the host it is visible, but with this problem of "No config found. + ECONNRESET". Medis does not report the error, but I believe it is the same thing because gives me a error. 

Doing the same process using the Redis-commaner stack (both Redis and commaner inside containers) does not work if I give the command below

Docker compose command: redis-server /usr/local/etc/redis/redis.conf
or

docker file CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

```
PS C:\Users\miche\Desktop\LAB\TEST> redis-commander
{ Error: ENOENT: no such file or directory, open 'C:\Users\miche\.redis-commander'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\miche\\.redis-commander' }
No config found or was invalid.
Using default configuration.
No Save: true
listening on  0.0.0.0 : 8081
Redis error Error: read ECONNRESET
    at _errnoException (util.js:1041:11)
    at TCP.onread (net.js:606:25)
No config found.
Using default configuration.
```

It is as if an external program outside of the container could not read the config file.

the log says "No config found. Using default configuration. " However, it does not access the Redis database. The Redis-Commander interface is broken without the possibility of adding keys.

The correct log should be

```
{ Error: ENOENT: no such file or directory, open 'C:\Users\miche\.redis-commander'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\miche\\.redis-commander' }
No config found or was invalid.
Using default configuration.
No Save: true
listening on  0.0.0.0 : 8081
Redis Connection localhost:6379 Using Redis DB #0
No config found.
Using default configuration.
loading keys by prefix ""
found 0 keys for ""

```

**Comment by yosifkit** [comment]
What is in your config file?

**Comment by MichelDiz** [comment]
Only:
################################## MODULES 
loadmodule /data/modules/libmodule.so
 loadmodule /data/modules/redisearch.so

But anyway I solved the problem using the Bitnami image. It was a lot easier actually. I should have done it at first. I reluctantly wanted to use the official image because of trust.

Although it solved my problem, the question remains. It's kind of complicated to make the official image work the way we want it. Predictably.

Cheers

**Comment by tianon** [comment]
So, Redis is kind of picky about its config file -- if you don't specify a config file, I've found that Redis uses a default set of configuration, but once you provide a configuration file then anything your configuration file doesn't specify gets a default value which is sometimes different from the default configuration without a configuration file.

For best results, I'd recommend copying the official Redis example configuration file (https://github.com/antirez/redis/blob/2bf8c2c1300da1909cc8c8c35d13e46bcf59aa31/redis.conf) any time you'd like to add or modify it in some way.
