### ISSUE TITLE
Can redis set environment variables like MySQL

### ISSUE THREAD

**Issue by jin10086** [docker-library/redis#113]
like 
```docker
  dbmaster:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: example
  dbslave:
    image: redis
    restart: always
    environment:
      MASTERPASS:example
```
the i can run redis cluster very quickly

I wanted to do it myself. but I'm bad at shell...

**Comment by leezzxuan** [comment]
have you get the solution? I've got the same problem

**Comment by yosifkit** [comment]
Closing as duplicate of #46.  There are [solutions](https://github.com/docker-library/redis/issues/46#issuecomment-211598784) discussed [there](https://github.com/docker-library/redis/issues/46#issuecomment-335326234).
