### ISSUE TITLE
Update to 4.0.5

### ISSUE THREAD

**Issue by ahfeel** [docker-library/redis#114]
4.0.4 introduced some highly critical bug leading to segv when replicating with lua scripts (see https://github.com/antirez/redis/commit/65a9740fa880a8e5b4640037a3670f8a2f33080b ).

Please update and publish new images ASAP :)

**Comment by kevin-brown** [comment]
It looks like this was done, the 4.0.5 images were pushed up to Docker Hub about 30 minutes ago.

**Comment by yosifkit** [comment]
Yup, all the architectures should all be up later today.
