### ISSUE TITLE
missing libgcc dependency for redis 4.0 on armhf for alpine 3.7

### ISSUE THREAD

**Issue by encodeering** [docker-library/redis#124]
Hi,

compilation was successful, but couldn't start redis-server due:

`Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/redis-server)`

Guess it would help to either

1. add libgcc package (http://pkgs.alpinelinux.org/package/v3.7/main/armhf/libgcc) or
2. create a static binary (https://blog.mx17.net/2015/06/30/statically-compile-redis-3-0-2-on-centos-5-rhel-5/)

I could create a pull request for 2. if you like

**Comment by yosifkit** [comment]
I think we just need something like [ruby](https://github.com/docker-library/ruby/blob/ca5366d8e8afa5f6cf810a07740a50e1f4eeab36/Dockerfile-alpine.template#L78-L92) has. That way we automatically detect dependencies and won't miss something like this in the future.

**Comment by encodeering** [comment]
Oh interesting part. I noticed that it makes a difference if you keep the build-dependencies installed, so probably it might be good to run this **after** `apk del`, but I really dont know how `scanelf` works. 
So it might work in either case.

**Comment by icebob** [comment]
Will it be fixed?

**Comment by encodeering** [comment]
Could you please run travis for the PR given above?

**Comment by yosifkit** [comment]
Fixed by #131.
