### ISSUE TITLE
Build for 4.0.8

### ISSUE THREAD

**Issue by anandanand84** [docker-library/redis#126]
Build for 4.0.8 not available in docker hub

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/redis" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/redis), especially [PRs with the "library/redis" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fredis). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

We'll probably be making an update many images PR later today.
