### ISSUE TITLE
Start Docker with redis.conf, docker logs without logs

### ISSUE THREAD

**Issue by arsenalpoll** [docker-library/redis#132]
Hi;
My `redis.conf` has `logfile` enabled
```
#cat redis.conf | grep logfile
logfile /data/redis/log/redis.log
```
Does not have any log output after `docker run`
`#docker  logs  -f redis` 

This is my Dockerfile
```
FROM redis
COPY docker-entrypoint.sh /usr/local/bin/
COPY redis.conf /usr/local/etc/redis/redis.conf

EXPOSE 6379
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["redis-server","/usr/local/etc/redis/redis.conf"]
```

**Comment by yosifkit** [comment]
That is correct. If you specify a logfile on disk, then the logs will not longer be sent to stdout and thus Docker will not see them. Docker only captures stdout/stderr of the container process for `docker logs`.
> ```
> # Specify the log file name. Also the empty string can be used to force
> # Redis to log on the standard output. Note that if you use standard
> # output for logging but daemonize, logs will be sent to /dev/null
> logfile ""
> ```
> \- https://github.com/antirez/redis/blob/d8207d09eedb08c8d70bff3ed91e2f5307e9dcf8/redis.conf#L168-L171

So, set it to the empty string and you can then see the logs in `docker logs` again.
