### ISSUE TITLE
docker pull winamd64/redis  error

### ISSUE THREAD

**Issue by faridabharmal** [docker-library/redis#139]
I am trying to pull a docker image on a windows 10 server using the following command and getting error. Any help shall be appreciated. 

docker pull winamd64/redis
Using default tag: latest
Error response from daemon: manifest for winamd64/redis:latest not found

Thanks
Farida

**Comment by tianon** [comment]
The Windows images are no longer supported, but if you look at https://hub.docker.com/r/winamd64/redis/tags/, you'll see that they never were available via `:latest`, and that you'll need to instead specify one of the tags that do exist (`windowsservercore`, etc).
