### ISSUE TITLE
WARNING overcommit_memory is set to 0

### ISSUE THREAD

**Issue by nimf** [docker-library/redis#14]
When I start container, I see this in logs:

`WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

I want data to be persistent. Should I worry about it?

**Comment by bkuhl** [comment]
This isn't a "run a container to solve a problem" kind of thing, but I appreciate there being containers running as part of a stack to help serve as documentation for what's been done to the host.  That said, I believe some folks may find https://github.com/bkuhl/redis-overcommit-on-host useful.

**Comment by adhil-bit** [comment]
- Container apicitywaycom-redis-1  Created                                                                                     0.0s
Attaching to apicitywaycom-redis-1
apicitywaycom-redis-1  | redis 06:46:40.93 
apicitywaycom-redis-1  | redis 06:46:40.94 Welcome to the Bitnami redis container
apicitywaycom-redis-1  | redis 06:46:40.94 Subscribe to project updates by watching https://github.com/bitnami/containers
apicitywaycom-redis-1  | redis 06:46:40.95 Submit issues and feature requests at https://github.com/bitnami/containers/issues
apicitywaycom-redis-1  | redis 06:46:40.95 
apicitywaycom-redis-1  | redis 06:46:40.95 INFO  ==> ** Starting Redis setup **
apicitywaycom-redis-1  | redis 06:46:41.02 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
apicitywaycom-redis-1  | redis 06:46:41.02 INFO  ==> Initializing Redis
apicitywaycom-redis-1  | redis 06:46:41.07 INFO  ==> Setting Redis config file
apicitywaycom-redis-1  | redis 06:46:41.18 INFO  ==> ** Redis setup finished! **
apicitywaycom-redis-1  | 
apicitywaycom-redis-1  | redis 06:46:41.24 INFO  ==> ** Starting Redis **
apicitywaycom-redis-1  | 1:C 14 Dec 2022 06:46:41.272 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
apicitywaycom-redis-1  | 1:C 14 Dec 2022 06:46:41.272 # Redis version=7.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
apicitywaycom-redis-1  | 1:C 14 Dec 2022 06:46:41.272 # Configuration loaded
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.273 * monotonic clock: POSIX clock_gettime
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.275 * Running mode=standalone, port=6379.
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.275 # Server initialized
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.275 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * Reading RDB base file on AOF loading...
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * Loading RDB produced by version 7.0.6
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * RDB age 887 seconds
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * RDB memory usage when created 0.82 Mb
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * RDB is base AOF
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * Done loading RDB, keys loaded: 0, keys expired: 0.
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * DB loaded from append only file: 0.000 seconds
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
apicitywaycom-redis-1  | 1:M 14 Dec 2022 06:46:41.276 * Ready to accept connections
