### ISSUE TITLE
Could not connect to Redis at 127.0.0.1:6379: Cannot assign requested address

### ISSUE THREAD

**Issue by magnum-ferox** [docker-library/redis#141]
redis-benchmark -c 150 -n 20000 -k 0

WARNING: keepalive disabled, you probably need 'echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse' for Linux and 'sudo sysctl -w net.inet.tcp.msl=1000' for Mac OS X in order to use a lot of clients/requests
====== PING_INLINE ======
  20000 requests completed in 1.23 seconds
  150 parallel clients
  3 bytes payload
  keep alive: 0

0.00% <= 1 milliseconds
0.50% <= 2 milliseconds
21.01% <= 3 milliseconds
42.46% <= 4 milliseconds
63.90% <= 5 milliseconds
85.35% <= 6 milliseconds
97.81% <= 7 milliseconds
98.68% <= 8 milliseconds
99.36% <= 9 milliseconds
99.76% <= 55 milliseconds
99.83% <= 56 milliseconds
99.93% <= 57 milliseconds
100.00% <= 57 milliseconds
16286.64 requests per second

Could not connect to Redis at 127.0.0.1:6379: Cannot assign requested address

root@fad3055c6e00:/data# echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
bash: /proc/sys/net/ipv4/tcp_tw_reuse: No such file or directory

**Comment by yosifkit** [comment]
Assuming that you are doing `docker exec` to run `redis-benchmark`, you need to run the redis container with `sysctl` if you want run the benchmark tool (see https://github.com/antirez/redis/issues/340).

```console
$ docker run -d --name red --sysctl net.ipv4.tcp_tw_reuse=1 redis
$ docker exec -it red bash
root@57c1b22a4f3f:/data# cat /proc/sys/net/ipv4/tcp_tw_reuse          
1
root@57c1b22a4f3f:/data# redis-benchmark -c 150 -n 20000 -k 0
## it still shows the warning but completes fine
```

**Comment by wglambert** [comment]
Issue seems resolved so going to close
