### ISSUE TITLE
Redis 5.0RC3 for Streams functionnalities ?

### ISSUE THREAD

**Issue by lakano** [docker-library/redis#145]
Hi,
Thanks a lot for your Redis official Docker images!
Any chance to get this version in your official repository please?
Regards,

https://raw.githubusercontent.com/antirez/redis/5.0/00-RELEASENOTES

**Comment by yosifkit** [comment]
We would like to provide them, but Redis does not release RC's in their regular channels; they are only available to download from github tags where the regular releases are on http://download.redis.io/releases/ and have hash verification via https://github.com/antirez/redis-hashes.

**Comment by lakano** [comment]
Ok, but why it's not possible to use the Github image version ? Because of the missing hash verification ?
I suppose RedisLabs create it without the hash verification, as you can see on there Docker Hub : https://hub.docker.com/r/redislabs/redis/

**Comment by tianon** [comment]
Ah, their download page does link to GitHub as the official release source for this RC: https://redis.io/download

I'll work on a PR. :+1:
