### ISSUE TITLE
[security] Push latest 3.2.12 / 4.0.10 images to Docker Hub

### ISSUE THREAD

**Issue by CpuID** [docker-library/redis#146]
For http://antirez.com/news/119

Looks like the bot auto committed the required changes. I assume it just needs a PR to [official-images](https://github.com/docker-library/official-images)? I tried to figure out the `bashbrew` side of things but gave up after a mins... :) I'm sure a maintainer here has things setup already.

**Comment by yosifkit** [comment]
https://github.com/docker-library/official-images/pull/4468
