### ISSUE TITLE
Redis v5.0-rc5

### ISSUE THREAD

**Issue by itamarhaber** [docker-library/redis#163]
I'm not seeing this at the hub and I don't know how to `sudo library-bot update redis with update.sh` :)

**Comment by tao12345666333** [comment]
I have updated it. 

Please see: https://github.com/docker-library/redis/pull/164

**Comment by itamarhaber** [comment]
So once merged, the bot will pick it up via JI - understood. Thanks!

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/4847 :+1:

**Comment by itamarhaber** [comment]
TY
