### ISSUE TITLE
Refuse connection on docker

### ISSUE THREAD

**Issue by iceoz** [docker-library/redis#167]
hi, i need help with a strange problem, i have a redis on docker with aof enabled, everything works fine until i began to use lock, after that for some reason the aof became locked on harddrive and i can't reuse my volume,
then i create two containers one with aof and other without aof to use with lock, everything seemsly fine but after two days container start refuse connection and docker log show nothing, i need to recreate the container. and then everything works again. 

it could be rdb? there is a way to disable rdb in docker? how to know if it is disabled for sure?

could be other problem? should i leave redis lock a search for other alternative?

**Comment by itamarhaber** [comment]
xref: https://github.com/antirez/redis/issues/5389

**Comment by iceoz** [comment]
@tao12345666333 lock means distributed lock,
this config command is inside redis cli?

**Comment by tao12345666333** [comment]
@iceoz  Yes, you can use redis-cli to do it.

**Comment by iceoz** [comment]
tks a create a image with the command
