### ISSUE TITLE
Redis v5 failure

### ISSUE THREAD

**Issue by sergey-morenets** [docker-library/redis#170]
Hi

I tried to run Redis 5 as Docker container: docker run -d -p 6379:6379 redis:5

However I always got an error:
C:\Program Files\Docker\Docker\Resources\bin\docker.EXE: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.

Thanks,
Sergey

**Comment by tao12345666333** [comment]
```
(MoeLove) ➜  ~ docker run -d -p 6379:6379 redis:5
Unable to find image 'redis:5' locally
5: Pulling from library/redis
f17d81b4b692: Already exists 
b32474098757: Already exists 
8980cabe8bc2: Already exists 
2719bdbf9516: Pull complete 
f306130d78e3: Pull complete 
3e09204f8155: Pull complete 
Digest: sha256:481678b4b5ea1cb4e8d38ed6677b2da9b9e057cf7e1b6c988ba96651c6f6eff3
Status: Downloaded newer image for redis:5
70f943d2b8db83f79c7942ff01eca3db1326327d7aa224469b28519dde632cd9
(MoeLove) ➜  ~ docker ps -al 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
70f943d2b8db        redis:5             "docker-entrypoint.s…"   8 seconds ago       Up 6 seconds        0.0.0.0:6379->6379/tcp   elastic_lichterman

```

It works for me **on Linux**.

Can you please run `docker pull redis:5` before `docker run` ? 

xref: https://github.com/docker-library/postgres/issues/296

**Comment by sergey-morenets** [comment]
Hi @tao12345666333 

I could resolve this issue only by resetting Docker factory settings. Some weird Docker issue.
Now it works propertly.

Thanks,
Sergey
