### ISSUE TITLE
PubSub losing connection in docker container redis

### ISSUE THREAD

**Issue by lucasalcantara** [docker-library/redis#172]
I have an app that does a PubSub to a Redis in docker container, and after my app receives 10k messages, Redis closes the connection of my app.
Any thoughts why this is happening? 

PS: I am publishing 1M messages to my PubSub

**Comment by itamarhaber** [comment]
xref: https://github.com/gomodule/redigo/issues/374
xref: https://stackoverflow.com/questions/53358036/redis-losing-connection-in-docker-container

**Comment by lucasalcantara** [comment]
It is not docker problem
