### ISSUE TITLE
what is default password to connect redis standalone image ?

### ISSUE THREAD

**Issue by rajweb2011** [docker-library/redis#173]
hi 

can some one please help me here as i have installed new image and its started fine with default host and port    to connect from my application what is the default password ?

**Comment by itamarhaber** [comment]
Hello @rajweb2011 

The default does not set a password.

**Comment by wglambert** [comment]
You can either supply a config file or pass config options through redis cli https://github.com/docker-library/redis/issues/46#issuecomment-211598784

**Comment by wkasunsampath** [comment]
If the connection string of the standalone docker redis is something like this,
`redis://default:redispw@localhost:32768`

Then,
Host: localhost
Port: 32768
Username: default
Password: redispw

**Comment by QAInsights** [comment]
The above one did not work, I was able to connect using 

```redis://host.docker.internal:6379```
