### ISSUE TITLE
redis cluster addslots error in version redis:4-alpine

### ISSUE THREAD

**Issue by Costriod** [docker-library/redis#179]
run a command like this:  redis-cli -h 172.20.0.15 -p 6379 cluster addslots {0..5461}, then (error) ERR Invalid or out of range slot returned. but this command that worked in version 3.2.12.

**Comment by wglambert** [comment]
`{num..num}` brace expansion is a [bashism](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html)

So in alpine's shell you could use `$(seq 5461)`
```console
$ docker run -dit -v $PWD/redis.conf:/usr/local/etc/redis/redis.conf --name redis redis:4-alpine redis-server /usr/local/etc/redis/redis.conf
e21bd077e3abdf2919ae92be81ec50aa4225f998c74e7ea51400330099f21a4b

$ docker exec -it redis sh
/data # redis-cli -h 127.0.0.1 cluster addslots $(seq 5461)
OK
/data # redis-cli -h 127.0.0.1 cluster slots
1) 1) (integer) 1
   2) (integer) 5461
   3) 1) ""
      2) (integer) 6379
      3) "784db4d38e114412de4e4919ade2b1847e8b7996"
/data #
```

**Comment by Costriod** [comment]
OIC, thanks

**Comment by PerfecterDay** [comment]
What is the correct syntax in windows ?
