### ISSUE TITLE
Starting redis with mount volume declaration 

### ISSUE THREAD

**Issue by Avik1993** [docker-library/redis#187]
hi
I am using the latest version of redis docker image.
When i am running the image withouth mount volume declaration, it works fine, but as soon as i include mount volume declaration while running it, container exits.
Command:
`docker run --name redis-tst -p 6380:6379 -d redis --appendonly yes -v /$Test/kompose-test/redis-data:/data`

When i inspect the logs, it says:
`*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
'appendonly "yes" "-v" /$TEST/kompose-test/redis-data:/data"'
Bad directive or wrong number of arguments
`

I also used `docker run -it --rm redis id` to check what should be the owner of data directory.
Output that i got was: `uid=0(root) gid=0(root) groups=0(root)`
so i have set owner of that directory to root.

What could be the issue here?

**Comment by itamarhaber** [comment]
Hello @Avik1993 

The order of arguments is important - `-v` should come before the arguments to the Redis server. The following should work:

```
docker run --name redis-tst -p 6380:6379 -v /$Test/kompose-test/redis-data:/data
 -d redis --appendonly yes 
```

**Comment by Avik1993** [comment]
Yes. Thanks :+1:  I figured that out moments after posting it here :)
