### ISSUE TITLE
Can not find the redis.conf

### ISSUE THREAD

**Issue by GarfieldZhan** [docker-library/redis#188]
I run a command like 

> docker run -it -d redis:5.0-alpine3.9
but I can't find redis.conf in the container

**Comment by chentging** [comment]
i can't find redis.conf in the container, are you already find it ?

**Comment by tao12345666333** [comment]
@chentging The redis docker image does not contain any `redis.conf` files.
xref: https://redis.io/topics/config
> Redis is able to start without a configuration file using a built-in default configuration, however this setup is only recommended for testing and development purposes.

> The proper way to configure Redis is by providing a Redis configuration file, usually called redis.conf.
