### ISSUE TITLE
Fatal error, can't open config file '-p'

### ISSUE THREAD

**Issue by PuKoren** [docker-library/redis#192]
I try to run the redis image on my computer:

```bash
$ docker run -it --name redis redis:5.0.5-alpine -p 6379:6379
1:C 05 Jun 2019 07:40:56.976 # Fatal error, can't open config file '-p'
```

I tried different tags, same result. Is there something special I should do ?

System: arch linux up to date (05-06-2019)

**Comment by Suresh-Kumar-A** [comment]
Thanks for this issue discussion, i too had the same issue. It would be great if docker provided this info in their docs or while showing error info
