### ISSUE TITLE
issues when build the images 5.05.

### ISSUE THREAD

**Issue by tonydeck0506** [docker-library/redis#195]
Dir sirs or madams,
I tried to use the Dockerfile to build a redis5.05 docker images. Unfortunately, it failed. the messages is as follows.
2019-06-25 08:57:09 (2.64 MB/s) - '/usr/local/bin/gosu.asc' saved [543/543]

+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.fKUEu46hTE
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keybox '/tmp/tmp.fKUEu46hTE/pubring.kbx' created
gpg: keyserver receive failed: Server indicated a failure
The command '/bin/sh -c set -ex; 		fetchDeps=" 		ca-certificates 		dirmngr 		gnupg 		wget 	"; 	apt-get update; 	apt-get install -y --no-install-recommends $fetchDeps; 	rm -rf /var/lib/apt/lists/*; 		dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; 	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; 	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; 	export GNUPGHOME="$(mktemp -d)"; 	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; 	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; 	gpgconf --kill all; 	rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; 	chmod +x /usr/local/bin/gosu; 	gosu nobody true; 		apt-get purge -y --auto-remove $fetchDeps' returned a non-zero code: 2

It seems it is relevant to the key server. do you have someway out?
thanks in advance.
Tony

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

If you run it some more times there's a decent chance it will eventually work
