### ISSUE TITLE
redis:3.2.9-alpine is not a multi-arch image

### ISSUE THREAD

**Issue by aojea** [docker-library/redis#199]
Is it possible to make it multi-arch or the recommendation is to use newer images?

xref: https://github.com/kubernetes/kubernetes/pull/79388#issuecomment-511119511

**Comment by mkumatag** [comment]
redis:3.2.9-alpine is almost a year old image which can't multi-arched as I see only 4.x and 5.x version images are dealt via `docker library` ci, the source can be found here - https://github.com/docker-library/redis

To solve this we have the following 2 possible solutions:

1. Use the higher version of redis image which is 4.x or 5.x
2. Enhance redis.conf at https://github.com/kubernetes/kubernetes/blob/master/test/images/redis/redis.conf to support IPv6

**Comment by aojea** [comment]
closing per previous comment
