### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by zhongyong** [docker-library/redis#208]
4.0 ok
5.0 run  logs 
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size

**Comment by tianon** [comment]
I'm not able to reproduce:

```console
$ docker pull redis:5.0
5.0: Pulling from library/redis
Digest: sha256:fe80393a67c7058590ca6b6903f64e35b50fa411b0496f604a85c526fb5bd2d2
Status: Image is up to date for redis:5.0

$ docker run -it --rm redis:5.0
1:C 23 Oct 2019 21:39:21.358 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 23 Oct 2019 21:39:21.358 # Redis version=5.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 23 Oct 2019 21:39:21.359 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 5.0.6 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 23 Oct 2019 21:39:21.361 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 23 Oct 2019 21:39:21.361 # Server initialized
1:M 23 Oct 2019 21:39:21.361 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 23 Oct 2019 21:39:21.361 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 23 Oct 2019 21:39:21.362 * Ready to accept connections
```

**Comment by zhongyong** [comment]
arm64  centos7.7
------------------ 原始邮件 ------------------
发件人: "Tianon Gravi"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 凌晨5:39
收件人: "docker-library/redis"<redis@noreply.github.com>;
抄送: "钟勇"<18455668@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [docker-library/redis] arm64 (#208)




I'm not able to reproduce:
 $ docker pull redis:5.0 5.0: Pulling from library/redis Digest: sha256:fe80393a67c7058590ca6b6903f64e35b50fa411b0496f604a85c526fb5bd2d2 Status: Image is up to date for redis:5.0 $ docker run -it --rm redis:5.0 1:C 23 Oct 2019 21:39:21.358 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo 1:C 23 Oct 2019 21:39:21.358 # Redis version=5.0.6, bits=64, commit=00000000, modified=0, pid=1, just started 1:C 23 Oct 2019 21:39:21.359 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf                 _._                                                              _.-``__ ''-._                                                    _.-``    `.  `_.  ''-._           Redis 5.0.6 (00000000/0) 64 bit   .-`` .-```.  ```\/    _.,_ ''-._                                     (    '      ,       .-`  | `,    )     Running in standalone mode  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379  |    `-._   `._    /     _.-'    |     PID: 1   `-._    `-._  `-./  _.-'    _.-'                                     |`-._`-._    `-.__.-'    _.-'_.-'|                                    |    `-._`-._        _.-'_.-'    |           http://redis.io           `-._    `-._`-.__.-'_.-'    _.-'                                     |`-._`-._    `-.__.-'    _.-'_.-'|                                    |    `-._`-._        _.-'_.-'    |                                     `-._    `-._`-.__.-'_.-'    _.-'                                          `-._    `-.__.-'    _.-'                                                  `-._        _.-'                                                          `-.__.-'                                                1:M 23 Oct 2019 21:39:21.361 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128. 1:M 23 Oct 2019 21:39:21.361 # Server initialized 1:M 23 Oct 2019 21:39:21.361 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect. 1:M 23 Oct 2019 21:39:21.361 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled. 1:M 23 Oct 2019 21:39:21.362 * Ready to accept connections

**Comment by yosifkit** [comment]
This sounds very silimar to https://github.com/docker-library/cassandra/issues/192.

**Comment by shenyongupc** [comment]
edit redis Dockerfile,
add 
```
sed -i 's/--enable-cc-silence/& --with-lg-page=16 /' /usr/src/redis/deps/Makefile;
```
to Dockerfile and rebuild it

**Comment by dragonhaimax** [comment]
> 4.0 ok
> 5.0 run logs
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size
> : Unsupported system page size

Have u solve the problem？

**Comment by zhongyong** [comment]
down src  and self make

**Comment by yuzp1996** [comment]
Is there any way to solve this problem?

**Comment by tianon** [comment]
As I noted above, we aren't able to reproduce the problem, and it's not something we're very comfortable patching upstream's code for -- if this is an issue with Redis upstream compiled from source in a non-Docker environment as well, I'd suggest coming up with a detailed reproducer (ideally with the appropriate fix, and details of why it is the correct fix more than just "this makes it work") and reporting it to the Redis project.

**Comment by yuzp1996** [comment]
[root@ecs-16b1-0002 ~]# uname -r
4.18.0-80.7.2.el7.aarch64
[root@ecs-16b1-0002 ~]# uname -a
Linux ecs-16b1-0002 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
[root@ecs-16b1-0002 ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (AltArch)
[root@ecs-16b1-0002 ~]# docker run redis:5.0.0
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size



That is what I meet on my machine，I find some blog said it is because of the jemalloc is different from my machine

**Comment by yuzp1996** [comment]
> [root@ecs-16b1-0002 ~]# uname -r
> 4.18.0-80.7.2.el7.aarch64
> [root@ecs-16b1-0002 ~]# uname -a
> Linux ecs-16b1-0002 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
> [root@ecs-16b1-0002 ~]# cat /etc/redhat-release
> CentOS Linux release 7.6.1810 (AltArch)
> [root@ecs-16b1-0002 ~]# docker run redis:5.0.0
> : Unsupported system page size
> : Unsupported system page size
> [root@ecs-16b1-0002 ~]# getconf PAGE_SIZE
> 65536
> 
> That is what I meet on my machine，I find some blog said it is because of the jemalloc when redis compile is different from my machine, It seems that I should compile on my machine to make sure the image can work on my machine

It work when I use the image  build on my own machine with dockerfile in 5.0 dir

**Comment by TravisLazar** [comment]
This seems related to this: [https://github.com/jemalloc/jemalloc/issues/467](https://github.com/jemalloc/jemalloc/issues/467 )

I can replicate this consistently when the host Kernel is running on aarch64 hardware with 64k page sizes - which is the default page size for most major Linux distributions on Arm. It seems to indicate that the redis image was built on a machine running with a 4k page size. 

Still doing further debug to completely verify that this is the exact issue.

**Comment by TravisLazar** [comment]
I have confirmed that rebuilding the redis image from source [using this tree](https://github.com/docker-library/redis/tree/master/6.0) on a system with 64k pages enabled fixes this issue. 

I have also confirmed that the pre-built images from DockerHub run out-of-the-box on a system with a 4k page size, but throw the aforementioned error with 64k page size. 

Is the build server for this running Ubuntu 18.04? That would explain this issue.

**Comment by tianon** [comment]
As a matter of fact, yes, the build server *is* on Ubuntu. :sweat_smile:

Is there some way to configure this at build-time so we don't have this issue?  Does having it built for 64k page sizes break the ability to use the image on systems with a 4k page size?

(How do distribution builds handle this issue?)

**Comment by tianon** [comment]
It looks like we probably need something like the following:

https://salsa.debian.org/debian/jemalloc/-/blob/c0a88c37a551be7d12e4863435365c9a6a51525f/debian/rules#L8-23

```makefile
# jemalloc supports a runtime page size that's smaller or equal to the build
# time one, but aborts on a larger one. If not defined, it falls back to the
# the build system's _SC_PAGESIZE, which in many architectures can vary. Set
# this to 4K on x86 for performance, and set it to 64K (2^16) on every other
# architecture, which should be a reasonable maximum. See Debian #843926, as
# well as upstream #467 for more context.
ifneq (,$(findstring $(DEB_HOST_ARCH),i386 amd64 kfreebsd-i386 kfreebsd-amd64 x32))
  DEB_CONFIGOPTS += --with-lg-page=12
else
  DEB_CONFIGOPTS += --with-lg-page=16
endif

# 2MB (2^21) is the default, but (as of 5.1.0) is overriden by whatever is
# found in /proc/meminfo. Avoid relying on the build system's configuration and
# just set it statically here.
DEB_CONFIGOPTS += --with-lg-hugepage=21
```

**Comment by tianon** [comment]
Heh, it also looks like perhaps https://github.com/redis/redis/blob/6f3b91fe26990f4c849d3f20269d69f3e3dc96f5/src/Makefile#L47-L55 should be updated to account for `aarch64`?  (or perhaps that's intentionally missing there, and expected to work reasonably; https://github.com/redis/redis/commit/4e9cf4cc7ed4b732fc4bb592f19ceb41d132954e)

**Comment by tianon** [comment]
https://github.com/redis/redis/blob/6f3b91fe26990f4c849d3f20269d69f3e3dc96f5/deps/Makefile#L91 :disappointed:

(It is difficult to add additional flags to `./configure` for `jemalloc` without patching.)

**Comment by tianon** [comment]
I've got a fix up in #254 -- if someone could test it on an affected system, that would be great!

(`docker build --pull 'https://github.com/docker-library/redis.git#refs/pull/254/head:6.0'`)

**Comment by tianon** [comment]
Ping :pray:

> I've got a fix up in #254 -- if someone could test it on an affected system, that would be great!
> 
> (`docker build --pull 'https://github.com/docker-library/redis.git#refs/pull/254/head:6.0'`)

**Comment by tianon** [comment]
Ok, I've made this simpler -- can someone with an affected system (where `redis:6.0` currently fails to run due to this issue) try running `fakeorg/redis:pr-254-arm64` and see if the problem is fixed?

**Comment by TravisLazar** [comment]
Hey Sorry! Somehow these notifications were going to spam. This fakeorg image makes it very easy for me to test. Let me spin up a system and try to reproduce the failure, then test this pr-254 image. I'll get back to you in a day-ish.

**Comment by TravisLazar** [comment]
@tianon 

I've confirmed your fix works on my aarch64 systems. Here's the series of steps I used to verify the error state as well as the fix state.

1. Bare-metal provisioned a fresh CentOS 8 install onto an aarch64 system.
2. Ran ```yum update```
3. Executed standard install process from Docker documentation (found [here](https://docs.docker.com/engine/install/centos/)).
4. Ran ```docker run -it redis:6.0```
5. After download, received expected page size error:

```
[sys ~]# docker run -it redis:6.0
Unable to find image 'redis:6.0' locally
6.0: Pulling from library/redis
4e6164a63b7b: Pull complete
66a6505e9bfd: Pull complete
fb4766a9fc53: Pull complete
42e04af4e1d2: Pull complete
a31c8ddc732f: Pull complete
a06a861805ec: Pull complete
Digest: sha256:33ca074e6019b451235735772a9c3e7216f014aae8eb0580d7e94834fe23efb3
Status: Downloaded newer image for redis:6.0
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```

6. Ran ```docker run -it fakeorg/redis:pr-254-arm64```
7. Redis runs as expected:

```
[sys ~]# docker run -it fakeorg/redis:pr-254-arm64
pr-254-arm64: Pulling from fakeorg/redis
4e6164a63b7b: Already exists
168ee33a4381: Pull complete
41e269d76523: Pull complete
0808df092db0: Pull complete
1157e9c8d49c: Pull complete
3bd01e64ea2b: Pull complete
Digest: sha256:5e2f035414fff3cb662012236c43bcf6200de5d19af637d5e8acdd7043bf1c40
Status: Downloaded newer image for fakeorg/redis:pr-254-arm64
1:C 24 Oct 2020 02:57:34.512 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Oct 2020 02:57:34.512 # Redis version=6.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
...
```

**Comment by tianon** [comment]
Excellent, thank you @TravisLazar!! :heart:
