### ISSUE TITLE
/proc/sys/net/core/somaxconn is set to the lower value of 128

### ISSUE THREAD

**Issue by YKanev** [docker-library/redis#211]
Hello guys,

I have here a problem setting up /proc/sys/net/core/somaxconn. It looks like there is no sysctl installed on the latest image.

When I run the latest redis image it gives me this message:
**_WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128_**

the command I used is 
**docker run --rm -p 6379:6379 -t image_id**

I cannot use --sysctl as this images will be used as a service in gitlab ci runner configuration.
Then it was not possible to do anything using redis-cli as an every command it keep dropping the connection.

Would you be able to give me some direction in order to solve this problem.
There will be more information of request as well.

Many thanks

Yordan

**Comment by wglambert** [comment]
The previous discussion on setting `somaxconn` https://github.com/docker-library/redis/issues/35

Essentially it has to be set at the host level. There's some gitlab issues related to this https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3817 https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3333 https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests/2707 

So this is a host configuration issue and not something we can alleviate in the image. It is just a warning however and the only issue would be if redis can't `accept()` fast enough from the (128 limit) accept queue then new connections to the preceding SYN queue start getting dropped, as opposed to a larger 511 sized accept queue https://blog.cloudflare.com/syn-packet-handling-in-the-wild/#slowapplication

**Comment by YKanev** [comment]
Thank you, wglambert.

Is there similar option in /etc/gitlab-runner/config.toml like this
[runners.docker.sysctls]
        "net.core.somaxconn" = "512"

But affecting the services!?
Many thanks

Yordan

**Comment by wglambert** [comment]
You should ask on one of the open issues about it since it's a gitlab-runner problem.

Going to close since there isn't anything we can change in the image to remedy an issue with the host's configuration
