### ISSUE TITLE
Build 6.0 with TLS support

### ISSUE THREAD

**Issue by J0WI** [docker-library/redis#215]
https://github.com/antirez/redis/blob/6.0/TLS.md

**Comment by tianon** [comment]
I'm wondering if this is maybe not actually fully implemented or not implemented exactly as documented there because when I build with `BUILD_TLS=yes`, I still can't get `redis-server` to accept `tls` related arguments:

```console
$ docker run ... --tls-port 6379 --tls-cert-file server.crt --tls-key-file server.key --tls-ca-cert-file cacert.pem

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'tls-port "6379"'
Bad directive or wrong number of arguments
```

**Comment by tianon** [comment]
The build output includes `-DUSE_OPENSSL`, and https://github.com/antirez/redis/blob/6.0-rc1/src/config.c#L2259-L2273 appears to corroborate that document, so I'm not sure what's going wrong here.
