### ISSUE TITLE
3.2-alpine has been removed but other 3.2.X-alpine tags still exist

### ISSUE THREAD

**Issue by nickjj** [docker-library/redis#222]
Hi,

Was there an accidental deletion of `redis:3.2-alpine` because it's no longer pullable, but `redis:3.2.10-alpine` is still available along with a few other 3.2.X releases.

If that was unintended can you please put `3.2-alpine` back?

**Comment by wglambert** [comment]
I'm able to pull it just fine
```console
$ docker pull redis:3.2-alpine
3.2-alpine: Pulling from library/redis
4fe2ade4980c: Pull complete 
fb758dc2e038: Pull complete 
989f7b0c858b: Pull complete 
42b4b9f869ad: Pull complete 
17e06138ef20: Pull complete 
c0ecd66db81e: Pull complete 
Digest: sha256:e9083e10f5f81d350a3f687d582aefd06e114890b03e7f08a447fa1a1f66d967
Status: Downloaded newer image for redis:3.2-alpine
docker.io/library/redis:3.2-alpine
```

**Comment by nickjj** [comment]
It's also available for me now too.

I had a few emails come in from people taking my Docker course saying it was dead, and at the time of opening this issue I was unable to pull it.

**Comment by tianon** [comment]
Yeah, this sounds like it was likely just a glitch due to the Alpine security updates we had yesterday that caused _everything_ to rebuild -- we don't typically remove tags on Docker Hub unless a maintainer explicitly requests that we do so (which is a very rare occurrence as well).

**Comment by tianon** [comment]
Oh actually, `redis:3.2-alpine` isn't even a currently-supported tag, so this had to have been a glitch on the Docker Hub side (if it isn't listed in https://github.com/docker-library/official-images/blob/master/library/redis, our build processes won't touch it).

**Comment by manishtomar** [comment]
> and at the time of opening this issue I was unable to pull it

@nickjj What was the error seen when trying to pull it?

**Comment by nickjj** [comment]
`redis:3.2-apline not found: manifest unknown`

This is going by what a few folks sent me. I already closed my terminal so I can't provide the full trace. I vaguely remember the the "json" being in there. Perhaps as part of a path where it looked to find it.
