### ISSUE TITLE
--restart option is not working with redis docker 

### ISSUE THREAD

**Issue by shanzhaozhen** [docker-library/redis#229]
Very strange ！，I can't user "--restart" option working in docker 

It's my docker run log
`
*** FATAL CONFIG FILE ERROR ***

Reading the configuration file, at line 1374

>>> 'restart "unless-stopped"'

Bad directive or wrong number of arguments

`

It's my run order
`
docker run -d \
    --name redis \
    -p 6379:6379 \
    -v /srv/dev-disk-by-label-NAS/soft/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf \
    -v /srv/dev-disk-by-label-NAS/soft/redis/data:/data \
    redis \
    /usr/local/etc/redis/redis.conf \
    --restart unless-stopped \
    --appendonly yes \
`

**Comment by wglambert** [comment]
Redis is reporting the config error because you gave that command to Redis and not Docker

Basically the same as
https://github.com/docker-library/postgres/issues/681#issuecomment-588472249
