### ISSUE TITLE
Redis 3.0.0 is out

### ISSUE THREAD

**Issue by stuartpb** [docker-library/redis#23]
See https://groups.google.com/forum/#!msg/redis-db/dO0bFyD_THQ/Uoo2GjIx6qgJ

I imagine this can essentially be added by copying the 2.8 content and changing the lines that have to do with 2.8 to 3.0?

**Comment by Starefossen** [comment]
It is already being discussed in #22 :smile:

**Comment by yosifkit** [comment]
This was completed. :smile:
