### ISSUE TITLE
Redis server is not responding 

### ISSUE THREAD

**Issue by chrismvp** [docker-library/redis#231]
Hi !
I have met problem with my redis server, because it is not responding any command !
What can I do?

![redis](https://user-images.githubusercontent.com/57568625/77679913-832f1d00-6f93-11ea-845c-46dba4ad2ae1.jpg)

**Comment by wglambert** [comment]
How's your system resources, did your container freeze or it just doesn't accept the `redis-cli` command?

Is there anything in the `docker logs` and what's your `docker version`
