### ISSUE TITLE
redis-6-rc4

### ISSUE THREAD

**Issue by bsergean** [docker-library/redis#236]
Hi there, fyi rc4 just got released -> https://github.com/antirez/redis/releases/tag/6.0-rc4

Thanks for providing docker images !

**Comment by tianon** [comment]
https://github.com/docker-library/redis/commit/f5c670afed78af489252e29157da974272188e77 + https://github.com/docker-library/official-images/pull/7839 :+1:

**Comment by bsergean** [comment]
Thank you !!
