### ISSUE TITLE
FATAL CONFIG FILE ERROR using default redis.conf

### ISSUE THREAD

**Issue by tayl** [docker-library/redis#239]
Hello,

I'm running into the following issue when following the steps at https://hub.docker.com/_/redis/

>*** FATAL CONFIG FILE ERROR ***
>Reading the configuration file, at line 335
>\>>> 'rdb-del-sync-files no'
>Bad directive or wrong number of arguments

if I comment out that entry, I get

>*** FATAL CONFIG FILE ERROR ***
>Reading the configuration file, at line 484
>\>>> 'repl-diskless-load disabled'
>Bad directive or wrong number of arguments

My Dockerfile is taken from the Redis Docker Hub as follows

>FROM redis
>COPY redis.conf /usr/local/etc/redis/redis.conf
>CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

and my redis.conf is taken from http://download.redis.io/redis-stable/redis.conf

I thought it might be a file encoding error, so I downloaded the exact bytes from the above URL but still faced this issue. Also tried redis:buster but had the same issues. The issue happens while using Docker desktop, as well as in our deployed AWS Fargate environment.

**Comment by tayl** [comment]
Of course, minutes after I post this I realize the issue. Redis Docker stable is 5, Redis.io stable is 6. The redis.io redis.conf file is incompatible with Stable Redis Docker.

**Comment by tianon** [comment]
Heh, Redis 6 only went GA today, and merged in https://github.com/docker-library/official-images/pull/7914 minutes ago, so please hold out just a tiny bit longer while it builds! :sweat_smile:
