### ISSUE TITLE
No dockerfile is present for building redis container on Ubuntu for power8 architecture 

### ISSUE THREAD

**Issue by MaheshWaidande** [docker-library/redis#24]
I have ported Redis to power8 architecture (ppc64le) and have also dockerized it on Ubuntu. I want to contribute docker files back to Redis community.  

I would like to know more about,
1. What is the correct way/procedure to commit/submit dockerfile to repository?
2. Is there any preference about naming convention of docker files and their place in repository?

**Comment by yosifkit** [comment]
It would be awesome to have multiple architectures for the official images. Unfortunately docker, the Docker Hub, and the Official Images program only officially support amd64 images, but hopefully this will change in the near future.

**Comment by tianon** [comment]
As of https://github.com/docker-library/redis/pull/37, the current `Dockerfile` should work as-is on ppc64le.

**Comment by tianon** [comment]
Oh, we're still using `wheezy`, which doesn't support `ppc64le`.  I'll send a PR to update that to `jessie` as well.

**Comment by tianon** [comment]
See https://github.com/docker-library/redis/pull/38 for the switch from `wheezy` to `jessie`.

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images#architectures-other-than-amd64 for the current "state of the art" on this subject.
