### ISSUE TITLE
Unable to pull redis:6

### ISSUE THREAD

**Issue by Void-Barrie** [docker-library/redis#241]
I can run redis:latest, but I can't get an image for redis:6, 6.0, or 6.0.0
docker run -it redis:6
Unable to find image 'redis:6' locally
6: Pulling from library/redis
docker: no matching manifest for linux/amd64 in the manifest list entries.

**Comment by tianon** [comment]
It was merged very recently in https://github.com/docker-library/official-images/pull/7914, and the builds are still in progress.  At this point it's just a matter of patience. :wink:
