### ISSUE TITLE
32Bit-tags of Redis 6 missing

### ISSUE THREAD

**Issue by joergLin** [docker-library/redis#245]
Since the stable release of version 6 there are no longer 32-Bit-Tags. The last tag is `6.0-rc-32bit`. Is this intentional? The version 5 tags have been updated regulary.

As far as I know there are still good reasons to use the 32Bit-variant if you run smaller instances. For reference:
* #28 
* https://redis.io/topics/memory-optimization#using-32-bit-instances

**Comment by tianon** [comment]
Use `--platform linux/386` or `i386/redis` directly (https://github.com/docker-library/redis/pull/219).
