### ISSUE TITLE
Master detects wrong IP for the slave nodes

### ISSUE THREAD

**Issue by erfansahaf** [docker-library/redis#248]
I'm trying to run a Redis cluster for replication and HA purposes:
```
===========                   =========== 
|  Master |   ------------>   |  Slave  | 
===========                   =========== 
IP: 180.xxx.xxx.xxx        IP: 200.xxx.xxx.xxx
Port: 6379                 Port: 6379
```

I use the following command to make a Redis node a slave:

```
// On machine 175.xxx.xxx.xxx

docker run -it redis bash
root@2b3186298d5a:/data# redis-cli
127.0.0.1:6379> replicaof 180.xxx.xxx.xxx 6379
OK
```
Here, the Redis says that the node has become a slave. With setting a key on master and fetching it on the slave, I can confirm that it's true. Also, the logs show that the SYNC process has successfully finished.

But when I run the `INFO REPLICATION` command on master node to see the replication status, it prints the local IP `172.27.0.1` as the slave IP address (while it should be `200.xxx.xxx.xxx`) :

```
# Replication
role:master
connected_slaves:1
slave0:ip=172.27.0.1,port=6379,state=online,offset=42,lag=1
master_replid:e499fd4626fe70772d81d27569f42ee62b2c3d87
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:42
second_repl_offset:-1
``` 

The wrong IP address of slaves leads to misconfiguration issues by the Sentinels. When the failover process starts, the Sentinel tries to make the `172.27.0.1` from a Slave node to a Master while there is no such Redis-Server reachable on that IP.

This issue only occurs when the Redis is running inside a docker container, not in the bare-mental setup.

Used Redis image: ```redis:6.0.5```

**Comment by wglambert** [comment]
Issues about redis clustering https://github.com/docker-library/redis/issues/190 https://github.com/docker-library/redis/issues/79
Doing a `docker exec redis-cli --cluster create ...` will use the container's external ip addresses

**Comment by erfansahaf** [comment]
If you are talking about [Redis Clustering](https://redis.io/topics/cluster-tutorial), it's not what I'm looking for. The Redis Cluster provides sharding and other features but I just want to have a replica node. But the code that you mentioned is for creating a Cluster, not a Replica node (as I know).

**Comment by yosifkit** [comment]
It looks like you are not using an overlay network and just running redis with `docker run -p 6379:6379` (and so it is behind the Docker nat). Did you set `replica-announce-ip`?
https://redis.io/topics/replication#configuring-replication-in-docker-and-nat

**Comment by erfansahaf** [comment]
@yosifkit I'm using Docker Compose in order to run the container and it uses Overlay as the network driver.
I had used `announce-ip` in sentinel configuration but this must be different. I will give it a try for the Redis itself.

**Comment by erfansahaf** [comment]
The problem solved with specifying `replica-announce-ip` and `replica-announce-port` . Thanks.
