### ISSUE TITLE
/proc/sys/net/core/somaxconn is set to the lower value of 128

### ISSUE THREAD

**Issue by kernelsky** [docker-library/redis#256]
Somaxconn is set in the system kernel, but it does not take effect when docker starts
[root@kube06 ~]# docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:50:02 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false
[root@kube06 ~]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
[root@kube06 ~]# docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:50:02 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false
[root@kube06 ~]# sysctl -p /etc/sysctl.d/kubernetes.conf
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.neigh.default.gc_thresh1 = 1024
net.ipv4.neigh.default.gc_thresh1 = 2048
net.ipv4.neigh.default.gc_thresh1 = 4096
vm.swappiness = 0
vm.overcommit_memory = 1
vm.panic_on_oom = 0
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches = 1048576
fs.file-max = 52706963
fs.nr_open = 52706963
net.ipv6.conf.all.disable_ipv6 = 1
net.netfilter.nf_conntrack_max = 2310720
net.core.somaxconn = 65535
[root@kube06 ~]# cat /proc/sys/net/core/somaxconn 
65535
[root@kube06 ~]# docker ps|grep redis-new
1e51af0395a4        redis                                                         "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes       0.0.0.0:6379->6379/tcp   redis-new
[root@kube06 ~]# docker logs redis-new
1:C 22 Oct 2020 02:20:28.182 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 22 Oct 2020 02:20:28.182 # Redis version=6.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 22 Oct 2020 02:20:28.182 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 22 Oct 2020 02:20:28.183 * Running mode=standalone, port=6379.
1:M 22 Oct 2020 02:20:28.183 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 22 Oct 2020 02:20:28.183 # Server initialized
1:M 22 Oct 2020 02:20:28.184 * Ready to accept connections

**Comment by kernelsky** [comment]
kubernetes has the same problem

[root@YK3PNEWOAW063 ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810
[root@YK3PNEWOAW063 ~]# sysctl -p
net.ipv4.ip_forward = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.neigh.default.gc_thresh1 = 1024
net.ipv4.neigh.default.gc_thresh2 = 2048
net.ipv4.neigh.default.gc_thresh3 = 4096
vm.swappiness = 0
vm.panic_on_oom = 0
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches = 1048576
fs.file-max = 52706963
fs.nr_open = 52706963
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 300
net.ipv4.tcp_max_syn_backlog = 262144
net.core.somaxconn = 65535
vm.overcommit_memory = 1
vm.max_map_count = 655360
[root@YK3PNEWOAW063 ~]# kubectl get pods|grep redis-public
redis-public-576f4d555d-4q8zc              1/1     Running   0          2d3h
[root@YK3PNEWOAW063 ~]# kubectl logs redis-public-576f4d555d-4q8zc -f
1:C 20 Oct 2020 10:12:21.249 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 20 Oct 2020 10:12:21.249 # Redis version=6.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 20 Oct 2020 10:12:21.249 # Configuration loaded
1:M 20 Oct 2020 10:12:21.251 * Running mode=standalone, port=6379.
1:M 20 Oct 2020 10:12:21.251 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 20 Oct 2020 10:12:21.251 # Server initialized
1:M 20 Oct 2020 10:12:21.251 * Ready to accept connections

**Comment by wglambert** [comment]
The previous discussion on setting `somaxconn` https://github.com/docker-library/redis/issues/35

Essentially it has to be set at the host level and is a host configuration issue, not something we can alleviate in the image. It's just a warning though and the only issue would be if redis can't `accept()` fast enough from the (128 limit) accept queue. Then new connections to the preceding SYN queue start getting dropped, as opposed to a larger 511 sized accept queue https://blog.cloudflare.com/syn-packet-handling-in-the-wild/#slowapplication

**Comment by tianon** [comment]
This is one of those fun cases where the status quo has changed :smile:

If you include `--sysctl` on your container, this value is scoped to the network namespace, and can thus be changed :partying_face:

```console
$ docker run -it --rm --sysctl net.core.somaxconn=511 bash
bash-5.0# cat /proc/sys/net/core/somaxconn
511
```
