### ISSUE TITLE
Unable to pull 6.0.10/6.2 with trust enabled.

### ISSUE THREAD

**Issue by miketroberts** [docker-library/redis#266]
Apologies if this isn't the right place to report this  (unsure if this is an issue with the image build, or with docker hub in general).

```
~/src → docker pull --disable-content-trust=false redis:6.0.10-alpine
No valid trust data for 6.0.10-alpine
~/src → docker pull --disable-content-trust=false redis:6.0.10
No valid trust data for 6.0.10
 ~/src → docker pull --disable-content-trust=false redis:6.2-rc3
No valid trust data for 6.2-rc3
```

This works for the previous images:

```
~/src → docker pull --disable-content-trust=false redis:6.0.9-alpine
Pull (1 of 1): redis:6.0.9-alpine@sha256:b0e84b6b92149194d99953e44f7d1fa1f470a769529bb05b4164eae60d8aea6c
docker.io/library/redis@sha256:b0e84b6b92149194d99953e44f7d1fa1f470a769529bb05b4164eae60d8aea6c: Pulling from library/redis
```

and for 5.0.10

```
~/src → docker pull --disable-content-trust=false redis:5.0.10-alpine
Pull (1 of 1): redis:5.0.10-alpine@sha256:e0256846c84d07095778890a8c481eceaca9a46a9d292a499555f40d248dfb29
```

Thanks.

**Comment by wglambert** [comment]
We don't have any involvement or insight into the signing process
https://github.com/nodejs/docker-node/issues/1065#issuecomment-514817797

**Comment by tianon** [comment]
Yep, as noted in https://github.com/docker-library/official-images/issues/1516, it's unfortunately been broken for quite some time now. :disappointed:

(Closing this one, since there's not really anything we can do at this level.)
