### ISSUE TITLE
Push images to grc.io or quay.io or ...

### ISSUE THREAD

**Issue by cdancy** [docker-library/redis#267]
Would it be possible to _also_ publish the redis images to some other registry so as to get around dockerhub rate-limiting?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/8998 (although I'd also note that these other registries have rate limits as well, just perhaps less conspicuous ones).

**Comment by cdancy** [comment]
Very good and thanks. Wasn't aware the other registries had rate-limits in place.
