### ISSUE TITLE
32 bit?

### ISSUE THREAD

**Issue by MrMMorris** [docker-library/redis#27]
I was wondering if it would possible to get a 32bit image. I have been trying to get my own built, but I can't seem to get it working. 

I added `libc6-dev-i386` to $buildDeps and removed `--no-install-recommends`. I then changed `make -C /usr/src/redis` to `make 32bit -C /usr/src/redis`. Everything builds fine.

Go to run it. `docker run redis`. Get `exec: "/entrypoint.sh": permission denied`. Add `RUN chmod +x entrypoint.sh`

Now when I try and run it, I get `error: exec failed: no such file or directory`. 

`ls -la /usr/local/bin` gives me:
```
total 8900
drwxrwsr-x  2 root staff    4096 Jul 15 19:02 .
drwxrwsr-x 13 root staff    4096 Jul 15 19:02 ..
-rwxr-xr-x  1 root staff 2141216 Jul 15 19:01 gosu
-rwxr-xr-x  1 root staff 1606733 Jul 15 19:02 redis-benchmark
-rwxr-xr-x  1 root staff   20055 Jul 15 19:02 redis-check-aof
-rwxr-xr-x  1 root staff   44651 Jul 15 19:02 redis-check-dump
-rwxr-xr-x  1 root staff 1711441 Jul 15 19:02 redis-cli
lrwxrwxrwx  1 root staff      12 Jul 15 19:02 redis-sentinel -> redis-server
-rwxr-xr-x  1 root staff 3574515 Jul 15 19:02 redis-server
```

Any idea what's going on? Am I taking the right approach?

Dockerfile: https://gist.github.com/b758f19378c719e3d42e

Entrypoint is the same

**Comment by MrMMorris** [comment]
Ah, just saw https://github.com/docker-library/redis/issues/24#issuecomment-106489406. 

Sadpanda

**Comment by MrMMorris** [comment]
Reopening in case there is a way

**Comment by larsks** [comment]
When you attempt to run a binary that definitely exists and you get a "no such file or directory" error, that almost invariably means you're missing the dynamic loader (`/lib*/ld-linux...`) appropriate to that file's architecture.

In this case, you need to install the `libc-i386` package:

    apt-get install libc6-i386

Once this is in place, redis runs without a problem:

    # redis-server
    460:C 15 Jul 19:53:57.168 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
    460:M 15 Jul 19:53:57.170 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
                    _._                                                  
               _.-``__ ''-._                                             
          _.-``    `.  `_.  ''-._           Redis 3.0.2 (00000000/0) 32 bit
      .-`` .-```.  ```\/    _.,_ ''-._                                   
     (    '      ,       .-`  | `,    )     Running in standalone mode
     |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
     |    `-._   `._    /     _.-'    |     PID: 460
      `-._    `-._  `-./  _.-'    _.-'                                   
     |`-._`-._    `-.__.-'    _.-'_.-'|                                  
     |    `-._`-._        _.-'_.-'    |           http://redis.io        
      `-._    `-._`-.__.-'_.-'    _.-'                                   
     |`-._`-._    `-.__.-'    _.-'_.-'|                                  
     |    `-._`-._        _.-'_.-'    |                                  
      `-._    `-._`-.__.-'_.-'    _.-'                                   
          `-._    `-.__.-'    _.-'                                       
              `-._        _.-'                                           
                  `-.__.-'

**Comment by tianon** [comment]
What's the use case for a 32bit variation?

(Especially one that's not actually a 32bit image, but is a 64bit image
that compiles a 32bit binary.)

**Comment by MrMMorris** [comment]
@tianon http://redis.io/topics/memory-optimization#using-32-bit-instances

**Comment by tianon** [comment]
Oh, since this is a supported upstream variation/configuration, I wouldn't
be opposed to a "redis:32bit" variant if we can work out the details.

**Comment by MrMMorris** [comment]
@tianon that would be lovely.

@larsks I can't seem to get it to work: https://gist.github.com/073740b54726ce915ee5

**Comment by larsks** [comment]
That's because of the `apt-get purge` later on in the Dockerfile. Take a look at the output of the `docker build` process:

    + apt-get purge -y --auto-remove gcc libc6-dev libc6-i386 make libc6-dev-i386
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following packages will be REMOVED:
      binutils* cpp* cpp-4.7* gcc* gcc-4.7* gcc-4.7-multilib* gcc-multilib*
      lib32gcc1* lib32gomp1* lib32itm1* lib32quadmath0* libc-dev-bin* libc6-dev*
      libc6-dev-i386* libc6-i386* libgmp10* libgomp1* libitm1* libmpc2* libmpfr4*
      libquadmath0* linux-libc-dev* make* manpages* manpages-dev*

You would need to add the `libc6-i386` package such that it does not
get removed by that purge operation.
