### ISSUE TITLE
RedisInsight image does not work on openshift

### ISSUE THREAD

**Issue by cyberb** [docker-library/redis#284]
I am trying to run RedisInsight image on openshift and it deos not seem to work. If I run it locally on plain docker it works fine.

I know openshift has more limitations than a local docker for example a special user id behaviour https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html

Can you tell me if openshift is supported?

**Comment by wglambert** [comment]
We don't maintain that `redislabs/redisinsight` image, I also can't seem to find any solid documentation on that particular image, given that the Dockerhub page also has no info on it, it seems the documentation is https://docs.redislabs.com/latest/ri/installing/install-k8s/

But yeah the `redis` image is an official image https://hub.docker.com/_/redis but `redislabs/redisinsight` is their own maintained image that the Docker Official Images team isn't involved with
