### ISSUE TITLE
issue starting the container on debian and alpine

### ISSUE THREAD

**Issue by docfactory37** [docker-library/redis#285]
I have build the code base locally, and it builds all fine but when i try and start the created container i get the below message.

![image](https://user-images.githubusercontent.com/20963053/125707532-7f59f2bb-37bb-4dad-b2ac-c71acd97ceb2.png)

i have tried with the Alpine and the Debian code and get the same issue.

**Comment by yosifkit** [comment]
If you are building the image from the files in the repo, then you need to either `git clone` or `chmod +x` the `docker-entrypoint.sh` script before building.

Related to https://github.com/docker-library/redis/pull/100

**Comment by docfactory37** [comment]
thank you for the quick response i will try that now on 6.2 and report back

**Comment by docfactory37** [comment]
i have adding the below in the dockerfile and it worked thank you for your help

`RUN chmod +x /usr/local/bin/docker-entrypoint.sh`
