### ISSUE TITLE
how to trigger update in dockerhub?

### ISSUE THREAD

**Issue by qrr1995** [docker-library/redis#289]
### Question 
Last week, there is a vulnerability issue that appeared in `redis:5.0.13-alpine`, which cause some security concerns in my team.

This week, I found that the image `redis:5.0.13-alpine` just pass the security scan, since there is a push at weekend, like this:

![image](https://user-images.githubusercontent.com/5809588/131961596-9f3ae3cd-b97e-4e94-a81e-897b104d41ef.png)

Thanks to the push, everything goes well!

### What I want 
The company I work for has quite strict security standards so I want to catch the fix ASAP.

Is this kind of `push`  scheduled?

If so, what's the scheduler, how can I trace the process?

**Comment by tianon** [comment]
You might find https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what and/or https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves useful -- neither *directly* answers your question, but together they provide the details you're looking for.

The short version is that an image is rebulit any time the source for that image changes or the base image is updated.
