### ISSUE TITLE
How can I seed data after redis-server has started using either Dockerfile or shell script ?

### ISSUE THREAD

**Issue by petef19** [docker-library/redis#292]
My issue is exactly as the title states. Tried a variety of things:

(1) tried seeding directly via `Dockerfile` using `RUN` or `CMD` - it never works as the server is not up and running yet
(2) tried seeding from another container, this works but do not want to spin up another container just to seed
(3) used a multi-stage build to ultimately seed and then transfer that `.rdb` to the actual `Redis` instance - this ultimately works
(4) tried to run a shell script at container start-up but it was never able to connect to the server-instance, even when waiting for 30s...

While some of these approaches work, all of this seems much way too complicated for such a simple task. Any other db system simply allows to place a `sql` file into the `/docker-entrypoint-initdb.d/` and it will simply be executed.

How can I achieve the equivalent for Docker `Redis` ? What is the recommended way to seed data at container start up ?

Thanks !

**Comment by tianon** [comment]
I'd suggest taking a look at the `docker-entrypoint.sh` scripts of those database images -- they're _extremely_ complex, and involve starting the database multiple times to accomplish this functionality.  If I could turn back the clock, I'd push harder against their inclusion (all that complexity is a constant source of bugs and misunderstandings). :sweat_smile:

Having a separate container (or even your application, on initial connection) initialize the database is much more reliable IME, and then works for managed database solutions too.
