### ISSUE TITLE
Add a way to enable overcommit memory in docker-entrypoint

### ISSUE THREAD

**Issue by Me-ion** [docker-library/redis#298]
From https://redis.io/topics/admin:
```
Make sure to set the Linux kernel overcommit memory setting to 1
```

Can we add something like following in the docker-entrypoint script to be run before the redis server is started
```
if [[ "$ENABLE_OVERCOMMIT_MEMORY" == 'true' ]]; then
	echo 1 > /proc/sys/vm/overcommit_memory
fi
```
then it would be really easy to enable that with:
```
docker run \
    -e ENABLE_OVERCOMMIT_MEMORY=true \
    ....
```

that would make it so much easier than creating a custom image and/or entrypoint script

**Comment by yosifkit** [comment]
Related issues. https://github.com/docker-library/redis/issues/19, https://github.com/docker-library/redis/issues/20, https://github.com/docker-library/redis/issues/55; This value is not namespaced and so must be set on the host as the container cannot set it.

```console
$ docker run -it --rm redis bash
root@deaa79bd3204:/# cat /proc/sys/vm/overcommit_memory 
0
root@deaa79bd3204:/# echo 1 > /proc/sys/vm/overcommit_memory 
bash: /proc/sys/vm/overcommit_memory: Read-only file system
root@deaa79bd3204:/# 
```

**Comment by tianon** [comment]
Another fun way to try and set this is via Docker's `--sysctl` flag which gives:

```
invalid argument "vm.overcommit_memory=1" for "--sysctl" flag: sysctl 'vm.overcommit_memory=1' is not whitelisted
```

**Comment by Adrian-Grimm** [comment]
> Related issues. #19, #20, #55; This value is not namespaced and so must be set on the host as the container cannot set it.
> 
> ```
> $ docker run -it --rm redis bash
> root@deaa79bd3204:/# cat /proc/sys/vm/overcommit_memory 
> 0
> root@deaa79bd3204:/# echo 1 > /proc/sys/vm/overcommit_memory 
> bash: /proc/sys/vm/overcommit_memory: Read-only file system
> root@deaa79bd3204:/# 
> ```


```bash
echo "vm.overcommit_memory=1" | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

cat /proc/sys/vm/overcommit_memory
```

**Comment by idan3** [comment]
@Adrian-Grimm does this solution really do the job?
Because I read configuring it from the container not working.

**Comment by tianon** [comment]
That suggestion is something to run on the host, not inside a container.
