### ISSUE TITLE
Cluster mode?

### ISSUE THREAD

**Issue by caarlos0** [docker-library/redis#30]
Redis has settings for [cluster mode](http://redis.io/topics/cluster-tutorial).

How can I use it with this image?

**Comment by caarlos0** [comment]
ignore me, I just figured it out, sorry

**Comment by craigpastro** [comment]
Wait? How did you do it? I am using cluster mode Redis for my app, but I also want to use test containers to test my app. Basically I just want to spin up a single node with clustered mode on to use for testing, but I can't seem to find out how to do that. Thanks!

**Comment by tianon** [comment]
> Requirements to create a Redis Cluster
> To create a cluster, the first thing you need is to have a few empty Redis instances running in cluster mode.
> 
> At minimum, set the following directives in the redis.conf file:
>
> ``` 
> port 7000
> cluster-enabled yes
> cluster-config-file nodes.conf
> cluster-node-timeout 5000
> appendonly yes
> ```
>
> To enable cluster mode, set the cluster-enabled directive to yes. Every instance also contains the path of a file where the configuration for this node is stored, which by default is nodes.conf. This file is never touched by humans; it is simply generated at startup by the Redis Cluster instances, and updated every time it is needed.
> 
> Note that the minimal cluster that works as expected must contain at least three master nodes. For deployment, we strongly recommend a six-node cluster, with three masters and three replicas.

(https://redis.io/docs/management/scaling/#requirements-to-create-a-redis-cluster)

**Comment by craigpastro** [comment]
Hi @tianon. Thanks for the comment! I have read that, but I just want to use one Redis container in clustered mode for testing purposes (my tests spin up a test container). My actual service uses clustered mode and the code to use clustered mode is different than the code to use non-clustered mode. If I could somehow pass an environment variable it would be great. I don't want to have to add a redis.conf file or `compose.yaml` just to spin up a test container.
