### ISSUE TITLE
Default config file

### ISSUE THREAD

**Issue by lliendo** [docker-library/redis#315]
Hi,

I have noticed that at least the docker `bullseye` Redis images does not provide a default config file. Would it be possible for next releases to include it? I believe is handy as if I want to tweak a setting the only thing I need to do is copy the default provided file alter it and update my docker image. Is there a reason not to include it?

Thanks in advance,
Lucas.

**Comment by tianon** [comment]
See also https://github.com/docker-library/redis/issues/300 -- I would suggest downloading one of the heavily-commented example files linked from https://redis.io/docs/manual/config/ as a starting point for tweaking configuration.
