### ISSUE TITLE
the dockerfile of redis-alpine image is not available

### ISSUE THREAD

**Issue by githublms** [docker-library/redis#318]
1. I checked the dockerfile file for building redis:alpine. It cannot be built locally through docker build.

2. The docker pulls the redis:alpine image directly and then runs. The redis service cannot be accessed.

3. I want to use the specified configuration file to start. What should I do?

![5a03bad546b768c2bc9d60cfce56b1d](https://user-images.githubusercontent.com/37056964/171077997-91e89bf8-2ef8-4bf2-9348-9b75ecace675.png)
![f079697bfb7f59c9d2940b770575317](https://user-images.githubusercontent.com/37056964/171078179-e4cbae5c-c2fc-4fd1-937e-a0e43b24a535.png)

**Comment by yosifkit** [comment]
> ```console
> $ docker run -it --rm redis:6-alpine /bin/sh
> ```

By adding `/bin/sh` you are choosing to not run redis server and instead run a shell.

This will start the redis server:

```console
$ docker run -d --name red redis:6-alpine
...
$ # get a shell in the container:
$ docker exec -it red /bin/sh

$ # or see what is running:
$ docker top red

$ # or stop it:
$ docker stop rm

$ # and clean up the stopped container:
$ docker rm red
```
