### ISSUE TITLE
Entrypoint error

### ISSUE THREAD

**Issue by Tjorriemorrie** [docker-library/redis#34]
I've run the following command on boot2docker:

> docker run --name redtest -d redis -p 6379:6379

But it gives the following error:

>/entrypoint.sh: line 9: exec: -p: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]

**Comment by Tjorriemorrie** [comment]
If you do a docker inspect you'll see that it regards the [ARGS] as the [COMMAND].

I suggest you properly add the CMD like elasticsearch:
```
# Add elasticsearch as command if needed
if [ "${1:0:1}" = '-' ]; then
	set -- elasticsearch "$@"
fi
```

**Comment by yosifkit** [comment]
It looks like you are trying to forward a port from the container, that option needs to be before the image that you are starting.  Everything after the image is interpreted as the arguments to running the container and becomes CMD for that run.
```diff
- docker run --name redtest -d redis -p 6379:6379
+ docker run --name redtest -d -p 6379:6379 redis
```
