### ISSUE TITLE
WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128.

### ISSUE THREAD

**Issue by sebicas** [docker-library/redis#35]
How can I get rid of this warning?

```
WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
```

I am using:

```
docker-machine version 0.4.1 (e2c88d6)
Boot2Docker version 1.8.2, build master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
Docker version 1.8.2, build 0a8c2e3
```

**Comment by Rooie** [comment]
Hi,

Came across this today while searching for a solution as I have the same issue. I found a possible solution to this. 

From: https://www.en0ch.se/performance-tips-for-redis-cache-server/

```
To fix this warning you have to set a new config to /etc/rc.local so that the setting will persist upon reboot

$~: sudo nano /etc/rc.local
Add this:

sysctl -w net.core.somaxconn=65535
When you reboot the next time, the new setting will be to allow 65535 connections instead of 128 as before.
```

Hope this will fix it for you.

Best regards,

Richard

**Comment by yosifkit** [comment]
Yeah that should work (depending on the init system of the docker host); this looks like a host configuration and I do not believe it can be set within a single container.

**Comment by tianon** [comment]
https://github.com/docker/docker/issues/4717 is the upstream Docker issue to keep track :+1:

**Comment by enoch85** [comment]
@Rooie, thanks for the link :)

**Comment by Rooie** [comment]
@enoch85 You're welcome! Glad to help :)

**Comment by enoch85** [comment]
@Rooie It's my site, thank you for linking it ;)

**Comment by Rooie** [comment]
Ah, I see. Thank you, for all the useful guides! The one for installing Redis really helped me out :) I also left a comment on your website!



Van: Daniel Hansson

Verstuurd: vrijdag 4 december 11:33

Onderwerp: Re: [redis] WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128. (#35)

Aan: docker-library/redis

Cc: Richard van Dijk



@Rooie It's my site, thank you for linking it ;)

**Comment by narikatel** [comment]
@Rooie thanks for the link :)

**Comment by enoch85** [comment]
@Rooie Can you please update from en0ch.se to techandme.se? I changed the domain. Thank you.

**Comment by jrsanz1** [comment]
Hey guys I'm having a really hard time with this one and I need help. I need to run a Redis container on a user defined network and assign it a static ip so I have this:
`docker run -v /root/test/:/data/ -p 7001:7001 --net iso_nw --ip 172.18.0.2 --name testy -d redis redis-server /data/redis.conf`
This causes my Redis instance to display the TCP backlog warning. My brain is fried trying to make this warning go away. Can someone help me please. Thanks.

**Comment by pataquets** [comment]
docker/docker#19265 just merged. Can this solve the issue?

**Comment by tianon** [comment]
Very cool -- that won't make it into 1.11 (being released today), but we could document for users of 1.12+ how they can use `--sysctl` on their `docker run` invocations in order to accomplish this. :+1:

**Comment by vingrad** [comment]
How can I use sysctl option with a compose file?

**Comment by billmccord** [comment]
@vingrad see here: https://github.com/docker/docker-py/pull/1145/files

**Comment by titpetric** [comment]
Unless I'm mistaken, there's currently no way to specify this with `docker service create`, so swarm mode is out of the question here? Even if somaxconn is larger on the host, it's not transferred to the running container(s). Any ideas?

**Comment by yosifkit** [comment]
@titpetric there is an issue tracking `service create` parity with `run`: https://github.com/docker/docker/issues/25303 and it links to https://github.com/docker/docker/issues/25209 for `--syscall` support (which you already commented on).  Without `--cap-add` there is no other workaround (other than patching and building your own kernel: `./include/linux/socket.h:#define SOMAXCONN	128`).

**Comment by titpetric** [comment]
@yosifkit Thanks, suggestion about recompiling the kernel noted. As far as work-arounds go, it's not bad - even if I usually cringe at "recompile your kernel" advice :) thanks.

**Comment by shkrid** [comment]
@titpetric @yosifkit 
I found such dirty hack http://stackoverflow.com/questions/26177059/refresh-net-core-somaxcomm-or-any-sysctl-property-for-docker-containers/26197875#26197875

**Comment by Gurpartap** [comment]
Before:

```
oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
...
# WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
...
```
I used the [--sysctl flag in docker](https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime):

```sh
$ /usr/bin/docker run --name redis \
                      --rm \
                      --sysctl net.core.somaxconn=511 \
                      --publish 127.0.0.1:6379:6379 \
                      redis:4.0-alpine
```

After:

```
# oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
# Redis version=4.0.2, bits=64, commit=00000000, modified=0, pid=1, just started
# Configuration loaded
* Running mode=standalone, port=6379.
# Server initialized
* DB loaded from disk: 0.000 seconds
* Ready to accept connections
```

No warning. Success.

**Comment by tianon** [comment]
:+1: thanks for confirming, @Gurpartap!

**Comment by askoretskiy** [comment]
Alternatively, you could force Redis to use TCP backlog for 128 entries:

    docker run redis:4-alpine redis-server --tcp-backlog 128

**Comment by JohnDavidLarsen** [comment]
Additionally in your docker-compose.yml you can provide options 

sysctls:
  net.core.somaxconn: '511'

https://docs.docker.com/compose/compose-file/#sysctls

//Some versions seem to need the single quotes, other versions don't, your results may vary.

**Comment by jmarcos-cano** [comment]
If somebody is struggling with this in swarm mode (swarm does not support it yet) go check my comment [here](https://github.com/moby/moby/issues/25209#issuecomment-361989766)

**Comment by farwish** [comment]
Anyone knows how to fix error below ?

Error Message:
```
ubuntu@VM-0-10-ubuntu:~/dk$ docker-compose up redis
Starting redis-con ... error

ERROR: for redis-con  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/core/somaxcomm: no such file or directory\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/core/somaxcomm: no such file or directory\"": unknown
ERROR: Encountered errors while bringing up the project.
```

docker-compose.yml:
```
version: '3'
services:
  redis:
    image: redis:3.2.12
    container_name: redis-con
    privileged: true
    sysctls:
      net.core.somaxcomm: '511'
```

**Comment by jxltom** [comment]
@farwish It is ```net.core.somaxconn```, not ```net.core.somaxcomm```

**Comment by horsecoin** [comment]
I don't get it, why is this not fixed if it is such an easy thing to do once?? I just am getting my reds started up following simple instructions, latest base ubuntu, just installed telnet, got my ports enabled, why in the world would this file not be edited for us???

ash: command substitution: line 1: unexpected EOF while looking for matching `''
bash: command substitution: line 3: syntax error: unexpected end of file
bash: -._: command not found
bash: $'-._-._-.__.-    _.-_.-|                                  \n |    `-._`-._        _.-_.-    |                                  \n  `-._    `-._`-.__.-_.-    _.-': command not found
root@2df0fd4fd94f:/#       `-._    `-.__.-'    _.-'                                       
bash: -._: command not found
bash: -.__.-    _.-: command not found
root@2df0fd4fd94f:/#           `-._        _.-'                                           
>               `-.__.-'                                               
> 
> 19:M 11 Apr 04:38:12.626 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> 19:M 11 Apr 04:38:12.626 # Server initialized
> 19:M 11 Apr 04:38:12.626 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> 19:M 11 Apr 04:38:12.626 * DB loaded from disk: 0.000 seconds
> 19:M 11 Apr 04:38:12.626 * Ready to accept connections
> sysctl -w net.core.somaxconn=65535
> ^C
root@2df0fd4fd94f:/# sudo nano /etc/rc.local
root@2df0fd4fd94f:/# echo never > /sys/kernel/mm/transparent_hugepage/enabled
bash: /sys/kernel/mm/transparent_hugepage/enabled: Read-only file system

-------

I am working through this slowly, just need to be able to telnet to meh redis port on my mac?

**Comment by tianon** [comment]
It's not "fixed" because it is not something we can fix in the image; it's
something you have to change in your environment.
