### ISSUE TITLE
Docker sunsets the free Team Organization feature 

### ISSUE THREAD

**Issue by christyjacob4** [docker-library/redis#351]
As you're aware, there has been a recent change in Docker's policy around their free Team Organization which will lead to all existing images to be deleted. More info here [https://news.ycombinator.com/item?id=35154025](https://news.ycombinator.com/item?id=35154025)

Since the `redis` image is also [hosted on DockerHub](https://hub.docker.com/_/redis), I wanted to check how this change will affect it and if we as consumers of the image should be concerned about it in any way or take any necessary steps.

**Comment by yosifkit** [comment]
All Docker Official Images are unaffected and will still continue to be maintained here via the `docker-library` org and hosted on Docker Hub.

Related: https://github.com/docker-library/official-images/issues/14258

**Comment by christyjacob4** [comment]
Thanks a lot for the clarification @yosifkit  👍
