### ISSUE TITLE
Execute shutdown command, causing the container to close together

### ISSUE THREAD

**Issue by fclever1122** [docker-library/redis#368]
![image](https://github.com/docker-library/redis/assets/126740207/83892ecc-3500-49e0-83de-698f9c4dbbe2)

After connecting to redis, the shutdown command is executed and the container is closed together. How can I stop the redis service without closing the container?

**Comment by yosifkit** [comment]
You can't; the Redis server process is the container. It is the container PID 1, so if it exits, the container exits. There are no other processes running in the container.
