### ISSUE TITLE
manifest for 7.2.0 is missing several platforms (including linux/amd64)

### ISSUE THREAD

**Issue by q0rban** [docker-library/redis#375]
I'm trying to pull the 7.2.0 tag from Docker hub, but it appears that perhaps the manifest is incomplete? `bookworm` has the linux/amd64 platform (and others), but 7.2.0 does not, even though they should be aliases. I was thinking maybe that the build was still in progress, but I've been checking back every few minutes and it's still not showing all of the platforms on the 7.2.0 tag.

`bookworm`
![redis Tags for bookworm showing 8 supported platforms](https://github.com/docker-library/redis/assets/66118/317a5488-33b7-45f9-a8a4-f15545aabffd)

`7.2.0`
![redis Tags for 7.2.0 only showing 3 supported platforms](https://github.com/docker-library/redis/assets/66118/40949895-7296-4ca4-bb25-db9d87923e49)

When building a Dockerfile for linux/amd64 that uses `FROM redis:7.2.0`, here is the error from `docker buildx build`:

```
Dockerfile:1
--------------------
   1 | >>> FROM redis:7.2.0
--------------------
ERROR: failed to solve: redis:7.2.0: no match for platform in manifest
```

**Comment by vladdblt** [comment]
Looks like fixed already
