### ISSUE TITLE
Missing signature key with Docker pull redis:latest (7.2.1) on OpenShift 3.11 nodes

### ISSUE THREAD

**Issue by mcraninx** [docker-library/redis#381]
Our OpenShift 3.11 compute nodes cannot pull redis:latest. The 'missing signature key' is thrown. Docker pull redis:7.2.1 has the same error and cannot be pulled. But docker pull redis:7.2.0 succeeds.

These compute nodes use Docker version 1.13.1, build 7d71120/1.13.1.

**Comment by yosifkit** [comment]
The `redis` image builds were recently moved to an upgraded builder using buildkit (to include provenance and an SBOM). It is likely that the old Docker client/daemon cannot handle the format.

Note the differences between the two image indexes: 
- `redis:7.2.0` image index on Docker Hub: https://explore.ggcr.dev/?image=redis%3A7.2.0
- `redis:latest` image index on Docker Hub: https://explore.ggcr.dev/?image=redis%3Alatest

Docker `1.13.1` was released in 2017 and should be updated to a supported release (currently `24.x`).

**Comment by drttcrh** [comment]
How to resolve it ? only upgrade ?

**Comment by tianon** [comment]
Yes, you need a newer, supported version of Docker.
