### ISSUE TITLE
Unable to Pull redis

### ISSUE THREAD

**Issue by RockmanR** [docker-library/redis#384]
I'm trying to pull redis but get the below error. I'm able to pull other other stuff, but not redis.

PS C:\Users\IT11325\dapr> docker pull redis
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/library/redis/manifests/sha256:d2f4d823a498f366c540b81e6b69bce397062f980f2e42340402225af0d9b5ab": EOF
PS C:\Users\IT11325\dapr>

**Comment by RockmanR** [comment]
"redis:5" works fine, but redis:6 and redis:7 fails with the above error.

**Comment by LaurentGoderre** [comment]
Try again? Maybe those tags were being updated while you were trying to pull

**Comment by RockmanR** [comment]
Ok, it turned out that the issue was from my company's firewall. After adding docker.io to the exeption list in the firewall, I was able to pull the image.
