### ISSUE TITLE
Doesn't save on SIGTERM

### ISSUE THREAD

**Issue by ericfrederich** [docker-library/redis#4]
According to http://redis.io/topics/signals Redis is supposed to do a save on SIGTERM:

> If Redis is configured to persist on disk using RDB files, a synchronous (blocking) save is performed. Since the save is performed in a synchronous way no additional memory is used.

According to http://docs.docker.com/reference/commandline/cli/#stop Docker sends a SIGTERM followed by a SIGKILL after a period (10 second default).

> The main process inside the container will receive SIGTERM, and after a grace period, SIGKILL

It seems to receive the SIGTERM and gracefully shutdown but it does so without a save.
Subsequent start of the container doesn't have the data.

    $ docker run --name some-redis -d redis
    4f9fd01b2ed8be449610c4210831b583c1c1f3db1e5560ed4c3921fee34f318d
    $ docker run -it --link some-redis:redis --rm redis sh -c 'echo set foo bar | redis-cli -h "$REDIS_PORT_6379_TCP_ADDR" -p "$REDIS_PORT_6379_TCP_PORT"'
    OK
    $ docker run -it --link some-redis:redis --rm redis sh -c 'echo get foo | redis-cli -h "$REDIS_PORT_6379_TCP_ADDR" -p "$REDIS_PORT_6379_TCP_PORT"'
    "bar"
    $ docker stop some-redis
    some-redis
    $ docker logs some-redis  | tail -n6
    [1] 25 Jul 15:25:58.611 # Server started, Redis version 2.8.12
    [1] 25 Jul 15:25:58.611 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
    [1] 25 Jul 15:25:58.611 * The server is now ready to accept connections on port 6379
    [1 | signal handler] (1406301986) Received SIGTERM, scheduling shutdown...
    [1] 25 Jul 15:26:26.770 # User requested shutdown...
    [1] 25 Jul 15:26:26.770 # Redis is now ready to exit, bye bye...
    $ docker start some-redis 
    some-redis
    $ docker run -it --link some-redis:redis --rm redis sh -c 'echo get foo | redis-cli -h "$REDIS_PORT_6379_TCP_ADDR" -p "$REDIS_PORT_6379_TCP_PORT"'
    (nil)

**Comment by miraage** [comment]
Next solution worked for me:
```yml
# docker-compose.yml
services:
  foo_redis:
    image: redis
    command: redis-server --appendonly yes
```

**Comment by jpetazzo** [comment]
The problem is back (caused by the "protected mode" workaround).

**Comment by tianon** [comment]
Poo :disappointed:

**Comment by tianon** [comment]
This might mean we have to patch the source to change the "protected mode" default value. :sob:

**Comment by tianon** [comment]
Seems like we could just modify https://github.com/antirez/redis/blob/a81a92ca2ceba364f4bb51efde9284d939e7ff47/src/server.h#L118 (`CONFIG_DEFAULT_PROTECTED_MODE`) after extracting and before compiling.  It's a pretty minor change, and since we build from source, it should be reasonably simple (and less fragile than our entrypoint hacking too).

**Comment by x-yuri** [comment]
For those interested in why

> It seems that if you specify any argument to redis-server, they assume you are going to specify everything.

welcome to the [adjacent issue][1].

[1]: https://github.com/docker-library/redis/issues/262#issuecomment-763259171

**Comment by ebuildy** [comment]
could we reopen it?

Our use case

On kubernetes, we use argo-workflow to run tests. Redis is deployed as a daemon:

```
  - name: redis-start
    daemon: true
    container:
      image: redis:6-alpine
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
      readinessProbe:
        exec:
          command:
          - redis-cli
          - ping
        initialDelaySeconds: 5
        periodSeconds: 2
        timeoutSeconds: 1
```

Run fine, when the workflow stop, redis stay because the SIGTERM stuff failed.

How run redis 100% on memory without the snapshot stuff please?

**Comment by yosifkit** [comment]
@ebuildy, I think that if you don't want persistence then either start redis with an empty `save` value, or set it via your testing setup (e.g. `redis-cli config set save ''`).

```console
$ # regular run
$ docker run -it --rm --name redi redis
...
^C1:signal-handler (1677110921) Received SIGINT scheduling shutdown...
1:M 23 Feb 2023 00:08:41.487 # User requested shutdown...
1:M 23 Feb 2023 00:08:41.487 * Saving the final RDB snapshot before exiting.
1:M 23 Feb 2023 00:08:41.499 * DB saved on disk
1:M 23 Feb 2023 00:08:41.499 # Redis is now ready to exit, bye bye...
$ docker exec -it redi redis-cli config get save
1) "save"
2) "3600 1 300 100 60 10000"

$ # no save run
$ docker run -it --rm --name redi redis --save
...
1:M 23 Feb 2023 00:08:49.650 * Ready to accept connections
^C1:signal-handler (1677110940) Received SIGINT scheduling shutdown...
1:M 23 Feb 2023 00:09:00.132 # User requested shutdown...
1:M 23 Feb 2023 00:09:00.132 # Redis is now ready to exit, bye bye...
$ .. $ docker exec -it redi redis-cli config get save
1) "save"
2) ""

```
