### ISSUE TITLE
A little description of entery-point.sh script

### ISSUE THREAD

**Issue by masifpak** [docker-library/redis#43]
#!/bin/bash
set -e
1- What is the purpose of "set -e" here.
if [ "$1" = 'redis-server' ]; then
	chown -R redis .
	exec gosu redis "$@"
2- What is the purpose of  this command  exec gosu redis "$@"
fi

exec "$@"

3- What is the Purpose of this command exec "$@" .

**Comment by bsodmike** [comment]
`set -e` causes the bash script to exit on error.

`exec gosu redis "$@"` This allows running the container like a binary, so any args passed in the `docker ...` call are passed along.  Check out [the README here](https://github.com/tianon/gosu) for more info on `gosu`.

`exec "$@"` is `redis-server` hasn't been passed an an argument, it'll run whatever was passed along.
