### ISSUE TITLE
start with persistent storage (/data/dump.rdb) volume-shared-filesystems

### ISSUE THREAD

**Issue by a1exus** [docker-library/redis#47]
I'm trying to "start with persistent storage" Redis docker using [Docker run reference](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems), however, inside of docker container I see `/data/dump.rdb` file, yet on host I do not:
```
alexus@mbp:~ $ docker run --name redis --volume=data:/data/:rw -p 6379:6379 -d redis
720d5faa3c90ae73bf0add2013fe074dd4bc14a6c30b6c593fa88646371efd4d
alexus@mbp:~ $ ls data/
alexus@mbp:~ $
```

please advise)

**Comment by yosifkit** [comment]
> The `container-dest` must always be an absolute path such as `/src/docs`. The `host-src` can either be an absolute path or a name value. If you supply an absolute path for the `host-dir`, Docker bind-mounts to the path you specify. If you supply a `name`, Docker creates a named volume by that `name`.
A `name` value must start with start with an alphanumeric character, followed by `a-z0-9`, `_` (underscore), `.` (period) or `-` (hyphen). An absolute path starts with a `/` (forward slash).
--[docs.docker.com](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems)

It looks like docker is treating that as a name for a volume rather than a path.  `docker inspect redis` should let you figure out where the docker managed volume is actually at.  If you just want it to store the data in the current directory, then this should work: `docker run --name redis --volume="$PWD/data":/data/:rw -p 6379:6379 -d redis`.

**Comment by a1exus** [comment]
per your recommendations, I tried your way, but with same results(`docker inspect redis` shows correct path to `/data`)
```
alexus@mbp:_Py $ docker run --name redis --volume="$PWD/data":/data/:rw -p 6379:6379 -d redis
8b1ab3d4f3da7947a1b847972252711271889367d8be1f08f286bd60a62c1b3e
alexus@mbp:_Py $ ls data/
alexus@mbp:_Py $ docker exec -it 8b1ab3d4f3da7947a1b847972252711271889367d8be1f08f286bd60a62c1b3e redis-cli
127.0.0.1:6379> save
(error) ERR
127.0.0.1:6379> 
alexus@mbp:_Py $ docker inspect redis | grep -A6 Mounts
    "Mounts": [
        {
            "Source": "/Users/alexus/X/data",
            "Destination": "/data",
            "Mode": "rw",
            "RW": true
        }
alexus@mbp:_Py $ 
```

**Comment by yosifkit** [comment]
We should implement a fix similar to https://github.com/docker-library/mongo/pull/81 (and the other issues linked there), but you can work around it with the following:

```
docker run -d --name redis --user 1000:50 -v $PWD/data:/data --entrypoint redis-server redis
```

Once we make the similar fix you wouldn't need the `--entrypoint` flag.

**Comment by a1exus** [comment]
seems fine now, I also _--appendonly yes_ for "persistent storage" - Do I still need to do that?)
```
$ docker run --detach --name redis --user 1000:50 --volume=$PWD/data:/data --entrypoint redis-server redis --appendonly yes
600cd340e803f765d1978b4f45410334aecb26e7005c2ade8ffc38bca6e57da9
$ docker exec -it $(docker ps --all --quiet --filter name=redis) redis-cli
127.0.0.1:6379> save
OK
127.0.0.1:6379> 
$ ls data/
appendonly.aof  dump.rdb
$ 

```

**Comment by yosifkit** [comment]
Yeah, you will still need that, since that is not the default.
