### ISSUE TITLE
gpg recv-keys not working

### ISSUE THREAD

**Issue by uromahn** [docker-library/redis#52]
In all your Dockerfiles, the command "gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4" fails for me with a timeout. This is because the default port used by gpg is blocked on my corporate firewall and instead I have to use port 80.

So the correct command which should work for everybody should be:
gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 0xB42F6819007F00F88E364FD4036A9C25BF357DD4

Please note the two changes:
1. the keyserver address has been fully qualified with protocol and port, and
2. the key ID has been preceeded with "0x" which is the correct syntax fot the keyserver being used.

**Comment by tianon** [comment]
Any particular reason you're building from source instead of using `FROM redis` and adding your customizations in a dependent `Dockerfile`?

**Comment by uromahn** [comment]
I am working at a company which has a policy to not use any software in production which does not come from

1. either a certified software vendor, or
1. from (open) source where we have done a high-level quality check and run some general security checks over the source code

You may call this overblown, but this is unfortunately my reality.
So, currently my only option to introduce Redis into our production environment as a Docker container is to build it from source.

The second reason is that your Dockerfile is based on Debian but our environment requires to use Ubuntu 14.04 LTS, so I have to build via source.

But even if I didn't need to build from source, isn't it good practice to make the Dockerfile work in any possible environment and hence adding the full specification to the keyserver URL?

**Comment by tianon** [comment]
> isn't it good practice to make the Dockerfile work in any possible environment

I'm honestly not sure I agree -- we can't make it work in _any_ possible environment, but as many as is reasonable I'm +1 on.

The problem is that we're currently using the "high availability" pool of keyservers, which don't universally support port 80 (AFAIK), and we have enough spurious failures even using that such that I wouldn't feel real great about switching to `p80` generally.  If there were a `p80` variant of the `ha` pool with the intersection of the two pools, I'd be +1 to using it (or even `hkps`).  See https://sks-keyservers.net/overview-of-pools.php for more about that.

**Comment by yosifkit** [comment]
> GPG keyservers being flaky is a problem we see all too often -- closing since there's not really anything actionable here.  As a workaround, I'd recommend either pulling the pre-built images as-is (and perhaps building upon them via `FROM mysql:XXX` in a derivative `Dockerfile`) or adjusting the keyserver to one which your own local environment has an easier time fetching from (such as `hkp://keyserver.ubuntu.com:80` or similar).
>
> \- https://github.com/docker-library/mysql/issues/263#issuecomment-354025886
