### ISSUE TITLE
Getting a REDIS_PORT env set to tcp://IP:6379 instead of 6379

### ISSUE THREAD

**Issue by kathiedart** [docker-library/redis#53]
Hi,

When linking this container with php, I'm getting a REDIS_PORT env being set to tcp://IP:6379 instead of 6379, which just gives me error after error about tcp://172.17.0.7:tcp://172.17.0.7:6379 not existing, which of course it doesn't. Any way we can actually make it a port by default?

At the moment I have to run my containers with -e "REDIS_PORT=6379".

Cheers

**Comment by tianon** [comment]
This is coming from Docker's linking feature (https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#environment-variables):
> Additionally, Docker creates an environment variable called `<alias>_PORT`. This variable contains the URL of the source container’s first exposed port. The ‘first’ port is defined as the exposed port with the lowest number. For example, consider the `WEBDB_PORT=tcp://172.17.0.82:5432` variable. If that port is used for both tcp and udp, then the tcp one is specified.

The solution I'd probably recommend right now is to use Docker's new networking features (https://docs.docker.com/engine/userguide/networking/dockernetworks/#user-defined-networks) to link containers together, which will allow for transparently supporting Docker Swarm and thus multi-host networking, but will also prevent these extra environment variables from being set.

**Comment by 5452** [comment]
same issue...

**Comment by tianon** [comment]
As I noted above, this is a feature of Docker itself (when using `--link`) which we cannot control or change.  If you need `REDIS_PORT` set to a different value, you'll need to do so explicitly. :+1:

**Comment by digglife** [comment]
This kind of feature should not be enabled by default. It takes me about 1 hour to track down why the hell my container has REDIS_PORT environment variable automatically... Thanks @tianon for explanation.

**Comment by maitrungduc1410** [comment]
This took me all day to see why my variable is override when running in Gitlab CICD with Redis as a service, it's linked with my job and cause the problem.

I was having a headache until reading this answer 💯
