### ISSUE TITLE
Move docker-entrypoint.sh to the root directory

### ISSUE THREAD

**Issue by maletor** [docker-library/redis#56]
I'm not sure what the convention is here but it would seem like the entrypoint script should live in the root directory judging from other official images.

```
xxxxxxxx_elasticsearch_1   /docker-entrypoint.sh elas
xxxxxxxx_neo4j_1           /docker-entrypoint.sh neo4j
xxxxxxxx_percona_1         /docker-entrypoint.sh mysqld
xxxxxxxx_redis_1           docker-entrypoint.sh redis
```

**Comment by yosifkit** [comment]
We've actually been slowly moving them to be in the path via [`/usr/local/bin`](https://github.com/docker-library/redis/blob/master/3.0/Dockerfile#L46) so that the `/` is not required, but we have kept a symlink in the root for backwards compatibility.

**Comment by maletor** [comment]
Sounds good. Feel free to close. At least on this lib 👍
