### ISSUE TITLE
can't use config file in cmd

### ISSUE THREAD

**Issue by reachlin** [docker-library/redis#62]
try to use:
command: ["redis-server", "/data/redis.conf"]

the error in log is:

redis_1 | **\* FATAL CONFIG FILE ERROR ***
redis_1 | Reading the configuration file, at line 2
redis_1 | >>> 'protected-mode "no" "/data/redis.conf"'
redis_1 | Bad directive or wrong number of arguments

**Comment by reachlin** [comment]
what is the right way to pass in a customized config in command now?

**Comment by reachlin** [comment]
also, find sth. strange on the folder mounted to /data/

lincai@arkam:~/devbox/onduty$ ls -l data
total 12
-rw-r--r-- 1 vboxadd vboxsf 6390 5月  12 16:58 dump.rdb
-rw-rw-r-- 1 vboxadd lincai   37 5月  12 17:25 redis.conf
l

**Comment by tianon** [comment]
Have you pulled the latest image?  What's in your `redis.conf`?  What flags are you passing to `docker run`?  (the main issue here should've been fixed by https://github.com/docker-library/redis/pull/61 :confused:)

**Comment by xaratt** [comment]
Same problem with lates image:
```
xaratt@xaratt:/tmp$ docker images | grep redis
xaratt@xaratt:/tmp$ docker pull redis
Using default tag: latest
latest: Pulling from library/redis
8b87079b7a06: Already exists 
a3ed95caeb02: Pull complete 
284e33235544: Already exists 
4f93af242dfb: Already exists 
8c429fec161a: Already exists 
77b759f85e4a: Pull complete 
53c576ba5ecc: Pull complete 
b02067e73d7e: Pull complete 
Digest: sha256:ddb31adb1f61405ee59fc9c569c2b09f1796d0f2190e78d84b873f2d930236c1
Status: Downloaded newer image for redis:latest
xaratt@xaratt:/tmp$ docker images | grep redis
redis                latest              be9c5a746699        2 weeks ago         184.9 MB
xaratt@xaratt:/tmp$ docker run -v /tmp/redis.conf:/tmp/redis.conf --name myredis redis redis-server /tmp/redis.conf
xaratt@xaratt:/tmp$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
52311776a1c6        redis               "docker-entrypoint.sh"   4 seconds ago       Exited (0) 2 seconds ago                       myredis
xaratt@xaratt:/tmp$ docker run  --name myredis redis 
<here redis start log>
```

And redis.conf:
```
xaratt@xaratt:/tmp$ cat /tmp/redis.conf 
daemonize yes
timeout 0
tcp-keepalive 60
logfile /tmp/redis-server.log
loglevel debug

save ""
stop-writes-on-bgsave-error no
appendonly no

maxmemory 32Mb
maxmemory-policy noeviction
```

Run host redis with same config:
```
xaratt@xaratt:/tmp$ telnet localhost 6379
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
xaratt@xaratt:/tmp$ redis-server /tmp/redis.conf 
xaratt@xaratt:/tmp$ telnet localhost 6379
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^]
telnet> Connection closed.
xaratt@xaratt:/tmp$ 
```

**Comment by zackgq2009** [comment]
got some issue. 
If run docker-redis `docker run -v /myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf --name myredis redis redis-server /usr/local/etc/redis/redis.conf`, the redis container can't run
if i run docker-redis `docker run -v /myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf -- name myredis2 redis`, the redis container can run normally, but if `docker exec -it myredis bash`, you will find the result of `redis-server /usr/local/etc/redis/redis.conf` is not work.

**Comment by tianon** [comment]
You need to remove "daemonize" from your config file.

**Comment by wglambert** [comment]
Issue seems resolved and/or a usability issue and not an error with the image.
