### ISSUE TITLE
protected-mode breaks options (ports, volumes, etc) used with docker run. 

### ISSUE THREAD

**Issue by BillBrower** [docker-library/redis#65]
I'm basically running into issue #60 in regards to options passed to docker run. Using this Dockerfile:

```
FROM redis:latest
COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
```

And this command:

```
docker run myredis -p 6379:6379
```

I get this error message:

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'protected-mode "no" "-p" "6379:6379"'
Bad directive or wrong number of arguments
```

**Comment by boxman0617** [comment]
I'm getting the same issue, how was this solved? @BillBrower

**Comment by tianon** [comment]
@boxman0617 have you verified that the configuration file you're specifying actually exists?

**Comment by boxman0617** [comment]
I figured it out. It seams that I was putting extra commands that where being passed to and internal script that would fail. Will post the commands when I get home.

**Comment by akashdathan** [comment]
remove the deamonize parameter from the config file
