### ISSUE TITLE
*** FATAL CONFIG FILE ERROR *** passing as parameter redis.conf file

### ISSUE THREAD

**Issue by antonioborondo** [docker-library/redis#67]
I am trying to create a **Redis cluster node** passing as parameter my own redis.conf file with the following configuration:

```
port 7000
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
```

I am running the following command to create the cluster node, which seems to be correct according with the [documentation](https://github.com/docker-library/docs/tree/master/redis#additionally-if-you-want-to-use-your-own-redisconf-):

```
docker run -v redis.conf:/usr/local/etc/redis/redis.conf --name node redis redis-server /usr/local/etc/redis/redis.conf
```

But I am getting the following error:

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'protected-mode "no" "/usr/local/etc/redis/redis.conf"'
Bad directive or wrong number of arguments
```

If I create my own Dockerfile to add the configuration file inside, it works perfect. But this is not the solution that I pursuit due I need to create nodes with different port numbers.

If I remove the port number from my configuration file, then I create my custom image named "redis-cluster-node" and finally I run the following command to pass the port as parameter:

```
docker run --name node redis-cluster-node -p 7000
```

I get the following error:

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'protected-mode "no" "-p" "7000"'
Bad directive or wrong number of arguments
```

My configuration file works fine with the [original project](https://github.com/antirez/redis) when I create a cluster node, so I presume the problem is related with the docker image itself or maybe I am missing something.

Can you help me with this? Thanks in advance! :smiley:

**Comment by yosifkit** [comment]
The error is definitely misleading.  I noticed that the volume path was not an absolute path and so that seemed to fix it. Here is what I did:

```diff
-docker run -v redis.conf:/usr/local/etc/redis/redis.conf --name node redis redis-server /usr/local/etc/redis/redis.conf

+docker run -v "$PWD"/redis.conf:/usr/local/etc/redis/redis.conf --name node redis redis-server /usr/local/etc/redis/redis.conf
```

If your volume is not an absolute path on the left (beginning in a `/`), then docker assumes that is the name of the volume it should create and manage.  It does show up in docker volumes, which would mean that `redis.conf` in the container is a folder, and the [entrypoint](https://github.com/docker-library/redis/blob/c49a42f6efcd2b971e43e93116a976b058035544/3.2/docker-entrypoint.sh#L23-L41) does not handle that well.
```console
$ docker volume ls
DRIVER              VOLUME NAME
local               redis.conf
```

**Comment by antonioborondo** [comment]
@yosifkit you are right! It works if I pass the absolute path of my redis.conf file :smile: 

However, the alternative passing the port number as parameter with the -p flag still does not work and I get the same error:

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'protected-mode "no" "-p" "7000"'
Bad directive or wrong number of arguments
```

**Comment by yosifkit** [comment]
It looks like all redis flags are `--` so that needs to be `--port 7000` to work.

**Comment by antonioborondo** [comment]
It works with --port. Thank you very much! :smile:

**Comment by itayB** [comment]
what about this one?
`docker run redis:5.0.4 --maxmemory_policy allkeys-lfu`
return:
```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 4
>>> 'maxmemory_policy "allkeys-lfu"'
Bad directive or wrong number of arguments
```

any idea how to fix it?
