### ISSUE TITLE
create a redis cluster in a single container, client connect failed due to container ip

### ISSUE THREAD

**Issue by ghost** [docker-library/redis#69]
i create a redis cluster with all nodes in one docker container, and expose all ports.
If i connect the cluster in the containers host, it can connect the container successful,
if i run: redis-cli -c -h [container host ip] -p 7000  on other host, I find that it try to connect the real ip of cluster node, that is the docker container's private ip(not the container host ip). so it fail always.

I'm not sure if this would helpful.

**Comment by crossz** [comment]
you have to do the port forwarding, i.e. "-p" for docker run or "ports:" for docker-compose by yourself.
