### ISSUE TITLE
Permissions on mounted /data volume not correct

### ISSUE THREAD

**Issue by marclennox** [docker-library/redis#7]
I'm running this instance with the /data directory mounted to the host machine with

```
-v /data/redis:/data
```

For some reason the permissions on the volume are not getting set properly despite the chown call in the Dockerfile, and therefore Redis pukes when trying to persist the DB.

Any ideas?

**Comment by ElvisTheKing** [comment]
same issue with mounted data dir

> docker run -v data:/data redis stat /data
  File: `/data'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d	Inode: 1051352     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)

**Comment by yosifkit** [comment]
The default `CMD` is `redis-server`, not `redis`, so it works just fine (`/entrypoint.sh redis-server`).  Here is the latest image id:
```console
$ docker images redis
REPOSITORY        TAG            IMAGE ID          CREATED           VIRTUAL SIZE
redis             latest         9216d5a4eec8      9 days ago        109.3 MB
```

**Comment by alexgorbatchev** [comment]
I'm having trouble getting this to work with docker machine & compose. Running docker in virtualbox env.

```
$ rm -fr tmp
$ docker-compose up
Starting test_redis_1
Attaching to test_redis_1
redis_1 | 1:M 17 Feb 20:06:08.714 # Can't open the append-only file: Permission denied
test_redis_1 exited with code 1
``` 

docker-compose.yml

```yml
version: "2"
services:
  redis:
    image: redis:3
    command: /entrypoint.sh redis-server --appendonly yes
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6379:6379"
```

The `./tmp/redis` folder is created but container can't write to it.

```

$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

$ docker-compose version
docker-compose version 1.6.0, build d99cad6
docker-py version: 1.7.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

$ docker-machine version
docker-machine version 0.6.0, build e27fb87
```

**Comment by marclennox** [comment]
I've found when host mounting data volumes, you often have to pre-create them and set the permissions to 999:999.  In some cases host mounting is very hard, such as with Postgres.  I've stopped doing host-mounting entirely and have embraced volume containers, which make these problems go away.

**Comment by yosifkit** [comment]
If you still want to mount data to a shared folder on your Mac, then because the entrypoint script currently only does a chown and user drop-down you should be able to do something similar to https://github.com/docker-library/redis/issues/47#issuecomment-187300472.

**Comment by chovy** [comment]
when i pre-create the directory `./mongo-data` with ownership of `ubuntu:ubuntu` and then I run `docker-compose up --build` it changes the owner to `999` and then docker gives a permission denied error.

**Comment by ahma0942** [comment]
Got the exact same problem as @chovy. Any fix to this?

**Comment by chovy** [comment]
https://stackoverflow.com/questions/61941469/my-local-volume-for-mongodb-gets-permission-deneied-when-running-docker-compose

**Comment by yosifkit** [comment]
@chovy, sorry I missed this. To use a local bind-mounted directory, you need to pre-create the directory (as you do) and then add `user` to the MongoDB service in the compose file with the ids of the owner of the directory (i.e. your `ubuntu` user and group; e.g. `user: "1000:1000"`).

If you do not pre-create the directory locally, then docker will create it as root owned when the container starts (and then the `mongo` container will be unlikely to have access and fail to start).

(The same applies to a bind-mounted redis data directory as well)

https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

**Comment by Yingsheng-eroad** [comment]
Have the same issue as @chovy, but mine is postgres.

**Comment by neuronflow** [comment]
same issue with redis and docker-compose..I run this setup on 3 machines and only one is affected on a regular basis, very weird.

**Comment by Yingsheng-eroad** [comment]
> same issue with redis and docker-compose..I run this setup on 3 machines and only one is affected on a regular basis, very weird.
This is my solution. Check if it helps.
https://stackoverflow.com/questions/61941469/my-local-volume-for-mongodb-gets-permission-deneied-when-running-docker-compose/62185391#62185391

**Comment by flimebelt** [comment]
I had the same problem.

create a .dockerignore file at the root of the building containing your data folder

![image](https://user-images.githubusercontent.com/77355215/105108840-eac1d600-5a99-11eb-997d-67c043804dfa.png)
