### ISSUE TITLE
Can't pull 3.2.3

### ISSUE THREAD

**Issue by andradei** [docker-library/redis#70]
```
docker pull redis:3.2.3
Pulling repository docker.io/library/redis
Tag 3.2.3 not found in repository docker.io/library/redis
```

On the other hand, `docker pull redis:3` gets me the images with Redis 3.2.2

**Comment by yosifkit** [comment]
There was a long queue in the image signing and scanning process; it should be up now.

**Comment by andradei** [comment]
It is, thank you.
