### ISSUE TITLE
8mb /core file

### ISSUE THREAD

**Issue by if-kenn** [docker-library/redis#72]
Is there a reason that there is what looks like a 8mb core dump file in the redis:3.2.3-alpine docker image? It does look like it compresses down to 28kb so it probably doesn't take up much space, but it still seems odd to just be hanging around.

It looks like it has been hanging around since June 23rd, 2016:

```
Access: 2016-06-23 21:59:02.000000000 +0000
Modify: 2016-06-23 21:59:02.000000000 +0000
```

It does not appear to be on the redis:3.0.7-alpine image.

**Comment by wglambert** [comment]
Doesn't seem to be an problem anymore, pruning old issue.
