### ISSUE TITLE
commands are executed twice within docker-entrypoint.sh of version 3.2

### ISSUE THREAD

**Issue by crossz** [docker-library/redis#76]
`exec gosu redis "$0" "$@"`
this in docker-entrypoint.sh makes above commands executed twice. such as following when I set -ex in it:

```
root@ubuntu:~/Desktop/redis/3.2/alpine# docker run -it --rm redis-orig
+ [ redis-server != redis-server ]
+ [ redis-server != redis-server ]
+ id -u
+ [ redis-server = redis-server -a 0 = 0 ]
+ chown -R redis .
+ exec su-exec redis /usr/local/bin/docker-entrypoint.sh redis-server
+ [ redis-server != redis-server ]
+ [ redis-server != redis-server ]
+ id -u
+ [ redis-server = redis-server -a 100 = 0 ]
+ exec redis-server
```

What's the purpose of this? why not just
`exec gosu redis "$@"`

**Comment by yosifkit** [comment]
It looks like it was just in case we were going to do more "work" after and to follow the pattern of other images, like [rabbitmq](https://github.com/docker-library/rabbitmq/blob/eb621e29e3e0b55ed949a3d6033131f681d4657a/docker-entrypoint.sh).
