### ISSUE TITLE
How can I start the Docker Redis container with my own pre-loaded dump.rdb?

### ISSUE THREAD

**Issue by jdejoode** [docker-library/redis#77]
I have been trying to start a Docker container that accepts my own dump.rdb as input. Is there a nice and clean way of doing this? So far I have not been successful. I am getting either permissions errors or protocol errors. Is there a way of fixing this?

**Comment by paulstanyer** [comment]
I have managed to do this like so:

`docker run -d --name mycontainer -v /local/path/to/dump.rdb:/data redis:latest`

**Comment by serezha93** [comment]
Me helped path directly to dump file, like `-v /local/path/to/dump.rdb:/data/dump.rdb`

**Comment by Coinhexa** [comment]
> I have managed to do this like so:
> 
> `docker run -d --name mycontainer -v /local/path/to/dump.rdb:/data redis:latest`

When you do this, the dump.rdb file is not deletable anymore. I am trying start a container, load a dump.rdb file, shut the container down and delete the file but it says "Operation not permitted" anymore when you try to delete the file. Is there a way to load a dump.rdb without making a volume. 
For example, start a docker redis container, copy a dump.rdb using docker cp and then restart redis to recognize this file?
