### ISSUE TITLE
Start Redis cluster

### ISSUE THREAD

**Issue by sparachi** [docker-library/redis#79]
I tried to use this Dockerfile and create a cluster. Have created the cluster instances based on this image. But I need to run "./redis-trib.rb create ... " command to setup the cluster configuration and I need to have ruby installed in the image. I tried couple of things but nothing seems to be working. Can you also update the dockerfile to include ruby installation.

**Comment by yosifkit** [comment]
Since ruby is not necessary to run `redis-server` I would be hesitant in adding it.  It should be simple to create a Dockerfile similar to the following:

```Dockerfile
FROM redis:3.2
RUN apt-get update && apt-get install -y ruby && rm -rf /var/lib/apt/lists/*
```

The it could be built by the automated build system of the Docker Hub or via your own deployment processes.

**Comment by dimthe** [comment]
@sparachi can you please explain/show you set up the cluster with this dockerfile please

**Comment by mmzhou** [comment]
I have the same problem too. @yosifkit now that there is no other efficient way to start a redis cluster, why we can't include ruby in this image? I feel it's necessary. Thanks!

**Comment by mmzhou** [comment]
Plus, why there is no file: redis-trib.rb in the image? Thanks!

**Comment by tianon** [comment]
The image only includes what's included in a standard Redis install -- if that file isn't included in the image, it's because it's not included by upstream during `make install`.

If that file were included, then having Ruby in the image by default might make more sense, but I'd rather not do so unless upstream officially recommends it (especially since adding Ruby is going to have a fairly significant effect on our image size, I'd imagine).

**Comment by tianon** [comment]
For those interested, that file appears to be available at http://download.redis.io/redis-stable/src/redis-trib.rb.

**Comment by yosifkit** [comment]
You don't need ruby in the redis nodes, just ruby to bootstrap the cluster:

```console
$ # create config files for the nodes
$ cat redis/redis.conf
port 6375
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
$ # create a network for them to talk on
$ docker network create redis-net
$ # start 6 nodes (you would probably want to bake the config in an image instead of the bind mount)
$ for red in 1 2 3 4 5 6; do \
  docker run -d -v "$PWD"/redis/:/usr/local/etc/redis/ \
  --name "redis-$red" --net redis-net \
  redis redis-server /usr/local/etc/redis/redis.conf; \
done
$ # run the redis-trib.rb script
$ docker run -it --rm --net redis-net ruby sh -c '\
  gem install redis \
  && wget http://download.redis.io/redis-stable/src/redis-trib.rb \
  && ruby redis-trib.rb create --replicas 1 \
  '"$(for red in 1 2 3 4 5 6; do \
    echo -n "$(docker inspect --format '{{ (index .NetworkSettings.Networks "redis-net").IPAddress }}' "redis-$red")"':6375 '; \
  done)"

>>> Creating cluster
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
172.20.0.2:6375
172.20.0.3:6375
172.20.0.4:6375
Adding replica 172.20.0.5:6375 to 172.20.0.2:6375
Adding replica 172.20.0.6:6375 to 172.20.0.3:6375
Adding replica 172.20.0.7:6375 to 172.20.0.4:6375
M: bdd9851c4da290e0b61794afee0f13825e00e2e0 172.20.0.2:6375
   slots:0-5460 (5461 slots) master
M: ce9bf375d937453fd201844879d53aa04ec0c31f 172.20.0.3:6375
   slots:5461-10922 (5462 slots) master
M: 7a63d49e7f751fcf0dc5bed8b69701efbd40e4de 172.20.0.4:6375
   slots:10923-16383 (5461 slots) master
S: cd1e320aef2b2f6a105e08fc6b90db71327a5354 172.20.0.5:6375
   replicates bdd9851c4da290e0b61794afee0f13825e00e2e0
S: 4edf33bd5f2f22672fede9dcc7bf2626c638a8a6 172.20.0.6:6375
   replicates ce9bf375d937453fd201844879d53aa04ec0c31f
S: 051ecb30f6099e62edbaedef95003e4dfa91befe 172.20.0.7:6375
   replicates 7a63d49e7f751fcf0dc5bed8b69701efbd40e4de
Can I set the above configuration? (type 'yes' to accept): yes
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join..
>>> Performing Cluster Check (using node 172.20.0.2:6375)
M: bdd9851c4da290e0b61794afee0f13825e00e2e0 172.20.0.2:6375
   slots:0-5460 (5461 slots) master
   1 additional replica(s)
S: cd1e320aef2b2f6a105e08fc6b90db71327a5354 172.20.0.5:6375
   slots: (0 slots) slave
   replicates bdd9851c4da290e0b61794afee0f13825e00e2e0
M: 7a63d49e7f751fcf0dc5bed8b69701efbd40e4de 172.20.0.4:6375
   slots:10923-16383 (5461 slots) master
   1 additional replica(s)
S: 051ecb30f6099e62edbaedef95003e4dfa91befe 172.20.0.7:6375
   slots: (0 slots) slave
   replicates 7a63d49e7f751fcf0dc5bed8b69701efbd40e4de
M: ce9bf375d937453fd201844879d53aa04ec0c31f 172.20.0.3:6375
   slots:5461-10922 (5462 slots) master
   1 additional replica(s)
S: 4edf33bd5f2f22672fede9dcc7bf2626c638a8a6 172.20.0.6:6375
   slots: (0 slots) slave
   replicates ce9bf375d937453fd201844879d53aa04ec0c31f
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
```

No, you cannot use hostnames unless this merges: https://github.com/antirez/redis/pull/2323.

**Comment by mmzhou** [comment]
@tianon redis-trib.rb was located in redis source code, it doesn't appear to this image just because it has been deleted after make. So I think it makes sense to integrate all necessary tools to run cluster. Isolating configuration is a main reason why we are using docker.

**Comment by mmzhou** [comment]
$ docker run -it --rm --net redis-net ruby sh -c '\
  gem install redis \
  && wget http://download.redis.io/redis-stable/src/redis-trib.rb \
  && ruby redis-trib.rb create --replicas 1 \
  '"$(for red in 1 2 3 4 5 6; do \
    echo -n "$(docker inspect --format '{{ (index .NetworkSettings.Networks "redis-net").IPAddress }}' "redis-$red")"':6375 '; \
  done)"

@yosifkit I feel not good each time I have to download and install new things when I create the cluster. Besides, It's also not good to assuming the hosting environment has python installed already.

**Comment by yosifkit** [comment]
There is no python in the example I provided; that is just bash on the host, and sh and ruby in the `ruby` container.  The only new things to download are the ruby image, the redis gem, and the `redis-trib.rb` file from redis.io (all of which could be bundled in a custom image via a Dockerfile).  What I was pointing out is that these items do not belong in the redis image since they are not required to run redis, but could be part of your own orchestration to create and manage a redis cluster.

**Comment by racc-costa** [comment]
@mmzhou please try this image [https://hub.docker.com/r/racccosta/redis/](https://hub.docker.com/r/racccosta/redis/). 
I already include the dependencies needed to run redis-trib.rb.

**Comment by boosh** [comment]
@yosifkit A good compromise would be to copy `redis-trib` to `/usr/local/bin` from the tarball. Then if anyone wants to run a cluster they could extend yours and just install ruby.

**Comment by boosh** [comment]
...Or provide an official `redis-trib` image like https://hub.docker.com/r/zvelo/redis-trib/

**Comment by akkizz** [comment]
I want to create a Redis cluster instance using docker file . I tried modifying the redis.conf and add below parameters : 

port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly no

But when i run the image with below command the instance runs as a Standalone.

_**sudo docker run -v /myredis/conf/redis.conf:/myredis/conf/redis.conf --name myredis redis redis-server /myredis/conf/redis.conf instance.**_

Any pointer for this would be helpful.
Thanks in advance.

**Comment by yu2003w** [comment]
@yosifkit  Is there any plan to release redis cluster orchestration solution for k8s, mesos?

**Comment by yosifkit** [comment]
@yu2003w, no plans for an auto-clustering image that I know of; we've been keeping the image as close to how upstream releases the software as possible.

@cihanb and @ushachar from upstream are now collaborating on the official-image, so maybe they have an opinion here?

**Comment by thesobercoder** [comment]
This is a really super needed feature. I wasted almost two days trying to figure this out.

**Comment by shankarshastri** [comment]
@yosifkit, Will redis-trib connect to the cluster without password?

**Comment by boosh** [comment]
BTW I managed to set up a redis cluster on k8s using a stateful set last year. But in the end the cluster was really flaky when a pod was terminated. IIRC I think it was because redis (2 at least) uses IPs instead of hostnames, but YMMV. I ended up running a standalone redis for each of my pods that needed a cache. It was a suboptimal approach, but more stable.

**Comment by godpit** [comment]
How to look the redis.conf with default. I can not find it.

**Comment by godpit** [comment]
docker run -p 6379:6379  -d redis redis-server --appendonly yes --cluster-enabled yes

It is work well with adding params.

**Comment by yosifkit** [comment]
It looks like `redis-trib.rb` has been deprecated since version 4 and there is now `redis-cli --cluster create`: https://redis.io/topics/cluster-tutorial#creating-the-cluster.  Since this `cluster create` needs to be done against already running redis instances, it will not be something that can be done automatically in the docker image.

https://redis.io/topics/cluster-tutorial#creating-the-cluster
https://redis.io/topics/replication
