### ISSUE TITLE
Can I use this image to build redis cluster?

### ISSUE THREAD

**Issue by hisi-SmallFish** [docker-library/redis#81]
Hi, All:
    I want to build a redis cluster and did as talked in http://redis.io/topics/cluster-tutorial .
    I wrote a config file locally like: 
 ```
              port 7000
              cluster-enabled yes
              cluster-config-file nodes.conf
              cluster-node-timeout 5000
              appendonly yes
```
And then I run the image with cmd `:docker run -v /data/docker/redis/7000/redis.conf:/usr/local/etc/redis/redis.conf --net=host --name redis_7000 -d 10.141.125.108:5000/redis /usr/local/etc/redis/redis.conf`

Then I tried to connect to this redis but failed. 

Then I got the inspect like this: ` "Hostname": "u107-234.huawei.com",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "6379/tcp": {}
            },
`

Does it affect?

How can I build a redis cluster correctly. Are there any official tutorial ?

3X~~~

**Comment by tianon** [comment]
Did you include your `cluster-config-file` (`nodes.conf` in the example you listed) in the container?  All I see in your `docker run` line is `redis.conf` itself mounted in.

**Comment by hisi-SmallFish** [comment]
But in the tutorial, they said human should never touch the nodes.conf, like follows:
`As you can see what enables the cluster mode is simply the cluster-enabled directive. Every instance also contains the path of a file where the configuration for this node is stored, that by default is nodes.conf. This file is never touched by humans, it is simply generated at startup by the Redis Cluster instances, and updated every time it is needed.`

**Comment by hisi-SmallFish** [comment]
Thank tianon, I know why now。

There is something wrong in my config file. Now the cluster plays well~~

`>>> Creating cluster
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
10.141.107.235:7001
10.141.107.234:7000
10.141.107.235:7003
Adding replica 10.141.107.234:7002 to 10.141.107.235:7001
Adding replica 10.141.107.235:7005 to 10.141.107.234:7000
Adding replica 10.141.107.234:7004 to 10.141.107.235:7003
M: 7648322e1c9f7094cbf32de9c4e97309eab84431 10.141.107.234:7000
   slots:5461-10922 (5462 slots) master
M: d97045136fbc268857c56c69000e529ddfb310fc 10.141.107.235:7001
   slots:0-5460 (5461 slots) master
S: 8e050c73dbe16425cc70729f6e4fa0566990cc5a 10.141.107.234:7002
   replicates d97045136fbc268857c56c69000e529ddfb310fc
M: 454550e39b4ba5716132d84470f4a794551e13e0 10.141.107.235:7003
   slots:10923-16383 (5461 slots) master
S: be521e734f57cf164ee391c435c39a0e399df2ee 10.141.107.234:7004
   replicates 454550e39b4ba5716132d84470f4a794551e13e0
S: fee9c9c3cf8dede584e2835a9f0fff158f85fef5 10.141.107.235:7005
   replicates 7648322e1c9f7094cbf32de9c4e97309eab84431
Can I set the above configuration? (type 'yes' to accept): yes
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join........
>>> Performing Cluster Check (using node 10.141.107.234:7000)
M: 7648322e1c9f7094cbf32de9c4e97309eab84431 10.141.107.234:7000
   slots:5461-10922 (5462 slots) master
   1 additional replica(s)
S: fee9c9c3cf8dede584e2835a9f0fff158f85fef5 10.141.107.235:7005
   slots: (0 slots) slave
   replicates 7648322e1c9f7094cbf32de9c4e97309eab84431
S: be521e734f57cf164ee391c435c39a0e399df2ee 10.141.107.234:7004
   slots: (0 slots) slave
   replicates 454550e39b4ba5716132d84470f4a794551e13e0
M: d97045136fbc268857c56c69000e529ddfb310fc 10.141.107.235:7001
   slots:0-5460 (5461 slots) master
   1 additional replica(s)
M: 454550e39b4ba5716132d84470f4a794551e13e0 10.141.107.235:7003
   slots:10923-16383 (5461 slots) master
   1 additional replica(s)
S: 8e050c73dbe16425cc70729f6e4fa0566990cc5a 10.141.107.234:7002
   slots: (0 slots) slave
   replicates d97045136fbc268857c56c69000e529ddfb310fc
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
`
