### ISSUE TITLE
hub.docker.com Readme for redis incorrectly states it is sponsored by Pivotal

### ISSUE THREAD

**Issue by cihanb** [docker-library/redis#88]
Hi team, thanks for maintaining the redis image on the hub. https://hub.docker.com/_/redis/ states that 
"Redis is an open-source, networked, in-memory, key-value data store with optional durability. It is written in ANSI C. The development of Redis has been sponsored by Pivotal since May 2013; before that..."

instead it should say
"Redis is an open-source, networked, in-memory, key-value data store with optional durability. It is written in ANSI C. The development of Redis is sponsored by Redis Labs today; before that, it was sponsored by Pivotal and VMware. ..."

**Comment by yosifkit** [comment]
Thanks! I added a PR to adjust the wording. https://github.com/docker-library/docs/pull/828.
