### ISSUE TITLE
Feature request: add HEALTHCHECK

### ISSUE THREAD

**Issue by rnavarropiris** [docker-library/redis#91]
Docker supports defining a command to determine if the container is running as intended (healthy), broken for some reason (unhealthy) or still initializing (starting):
* https://docs.docker.com/engine/reference/builder/#healthcheck

Adding this to this image with the semantic "the redis store is online and functional" would be quite nice.

Since the last HEALTHCHECK defined by a Dockerfile is the one actually used, images based on this one could define their own healthcheck without "interference" by the one provided by the redis image.

**Comment by rturk** [comment]
This can be really helpful when running this image in a Kubernetes cluster

**Comment by yosifkit** [comment]
Copying comment from https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271

> I do not feel that generalized healthchecks on the official images are really that useful. 
>- users will have their own idea of what is "healthy"
>- it does not actually test that the service is listening to connections outside of `localhost` (see https://github.com/docker-library/healthcheck for some examples that do more than what's proposed here, including attempting to check whether the service is listening remotely)
>   - some of the Official Images even purposely start in a `localhost` only mode for database initialization and then kill and start the main service with full network availability
>- after upgrading their images, current users will have extra unexpected load on their systems for healthchecks they don't necessarily need/want and may be unaware of

**Comment by rturk** [comment]
@yosifkit humbly disagree with your comment, any service should report if can perform what is expected/required to do.

**Comment by rnavarropiris** [comment]
@yosifkit 
I also disagree, please see [this comment](https://github.com/docker-library/postgres/issues/282#issuecomment-311051076)

**Comment by tiredpixel** [comment]
@yosifkit, I also respectfully disagree. Please see my comment https://github.com/docker-library/postgres/issues/282#issuecomment-311299421.

**Comment by wglambert** [comment]
Copying comment from https://github.com/docker-library/cassandra/pull/76#issuecomment-426816911

> I still don't think healthchecks should be added to official images.
> 
> - the docker defined ones are disabled when using kubernetes (https://github.com/kubernetes/kubernetes/pull/50796) since it conflicts with their own [`liveness` and `readiness` probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/)
> - they do not require a custom Dockerfile and can be defined in the `docker-compose.yml` (or `stack.yml` for swarm)
>   - some example healthchecks are provided in the aforementioned https://github.com/docker-library/healthcheck
> - sometimes systems are slow and a default healthcheck could kill the container early and prevent the system from ever properly initializing (https://github.com/docker-library/mysql/issues/439)

**Comment by tianon** [comment]
Indeed, see also https://github.com/docker-library/faq#healthcheck.

**Comment by tgross35** [comment]
Very late to the party but for anyone from the future -

In general I feel that healthchecks shouldn't be enabled by default. However, it certainly isn't a bad idea to provide and document a good basic healthcheck (script included in image, command, etc) - something along the lines of "the running service considers itself to be healthy if X, and 80%+ of users would probably agree". 

We're in luck; redis already has this. The following compose tidbit works well:

```yaml
healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    timeout: 10s
    retries: 3
    start_period: 10s
```

The command returns `PONG` if the ping successfully connects. Won't catch everything but is at least enough to report that redis is up and running.
